import classes.TJMaterials
import com.fulltrix.gcyl.materials.GCYLMaterials
import gregtech.api.fluids.FluidBuilder
import gregtech.api.fluids.FluidState
import gregtech.api.fluids.store.FluidStorageKeys
import gregtech.api.unification.material.Material
import gregtech.api.unification.material.Materials
import gregtech.api.unification.material.event.MaterialEvent
import gregtech.api.unification.material.info.MaterialFlags
import gregtech.api.unification.material.info.MaterialIconSet
import gregtech.api.unification.material.properties.BlastProperty

event_manager.listen { MaterialEvent event ->
    TJMaterials.PahoehoeLava = Material.builder(10000, resource(getPackId(), 'pahoehoe_lava'))
            .fluid(FluidStorageKeys.LIQUID, FluidState.LIQUID)
            .color(0x964B00)
            .flags(MaterialFlags.GLOWING)
            .build()
    TJMaterials.StarMetalAlloy = Material.builder(10001, resource(getPackId(), 'star_metal_alloy'))
            .color(0x050A30)
            .iconSet(MaterialIconSet.SHINY)
            .liquid(new FluidBuilder().temperature(7000))
            .ingot(3)
            .dust()
            .flags(MaterialFlags.GENERATE_PLATE, MaterialFlags.GENERATE_DOUBLE_PLATE)
            .blast(b -> b.temp(7000, BlastProperty.GasTier.HIGH)
                    .blastStats(8000, 1716)
                    .vacuumStats(8000, 438))
            .build()
    TJMaterials.RawChaos = Material.builder(10002, resource(getPackId(), 'raw_chaos'))
            .color(0x000000)
            .liquid()
            .build()
    TJMaterials.DraconicStemCell = Material.builder(10003, resource(getPackId(), 'draconic_stem_cell'))
            .color(0xFF0000)
            .liquid()
            .build()
    TJMaterials.EternityPreparation = Material.builder(10004, resource(getPackId(), 'eternity_preparation'))
            .color(0x46008B)
            .iconSet(MaterialIconSet.SHINY)
            .dust()
            .build()
    TJMaterials.Eternity = Material.builder(10005, resource(getPackId(), 'eternity'))
            .color(0x46008B)
            .plasma()
            .build()
    TJMaterials.HMX = Material.builder(10006, resource(getPackId(), 'hmx'))
            .color(0xF3FFDB)
            .iconSet(MaterialIconSet.SHINY)
            .dust()
            .build()
    TJMaterials.NaquadricFuelCatalyst = Material.builder(10007, resource(getPackId(), 'naquadric_fuel'))
            .color(0x130642)
            .iconSet(MaterialIconSet.SHINY)
            .dust()
            .build()
    TJMaterials.Octaazacubane = Material.builder(10008, resource(getPackId(), 'octaazacubane'))
            .color(0x5F5FD9)
            .iconSet(MaterialIconSet.SHINY)
            .dust()
            .build()
    TJMaterials.OctaazacubaneSolution = Material.builder(10009, resource(getPackId(), 'octaazacubane_solution'))
            .color(0x5F5FD9)
            .iconSet(MaterialIconSet.SHINY)
            .liquid()
            .build()
    TJMaterials. StarlightComplex = Material.builder(10010, resource(getPackId(), 'starlight_complex'))
            .color(0xE1FAF7)
            .liquid()
            .build()
    TJMaterials.ExplosiveHydrazineMixture = Material.builder(10011, resource(getPackId(), 'explosive_hydrazine'))
            .color(0x3B0C5C)
            .liquid()
            .build()
    TJMaterials.StarlightRocketFuel = Material.builder(10012, resource(getPackId(), 'starlight_fuel'))
            .color(0xDF362D)
            .iconSet(MaterialIconSet.SHINY)
            .liquid()
            .build()
    TJMaterials.StellarAlloy = Material.builder(10013, resource(getPackId(), 'stellar_alloy'))
            .color(0xFFEFB5)
            .liquid()
            .build()
    TJMaterials.UnfiredClay = Material.builder(10014, resource(getPackId(), 'unfired_clay'))
            .iconSet(MaterialIconSet.ROUGH)
            .color(0x51010A)
            .dust(1)
            .build()
    Materials.Protactinium.addFlags(MaterialFlags.GENERATE_FRAME)
    Materials.NeodymiumMagnetic.addFlags(MaterialFlags.GENERATE_GEAR)
    Materials.Osmium.addFlags(MaterialFlags.GENERATE_DENSE)
    Materials.Ruthenium.addFlags(MaterialFlags.GENERATE_DENSE)
    Materials.Cobalt.addFlags(MaterialFlags.GENERATE_GEAR)
    GCYLMaterials.Draconium.addFlags(MaterialFlags.GENERATE_DOUBLE_PLATE)
}