import appeng.api.util.AEColor
import appeng.core.Api
import appeng.core.ApiDefinitions
import classes.TJMaterials
import com.fulltrix.gcyl.item.GCYLCoreItems
import com.fulltrix.gcyl.materials.GCYLMaterials
import com.fulltrix.gcyl.materials.GCYLNuclearMaterials
import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.MarkerMaterials
import gregtech.api.unification.material.Material
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.items.MetaItems
import gregtech.common.metatileentities.MetaTileEntities

ApiDefinitions definitions = Api.INSTANCE.definitions()

// certus quartz block
RecipeMaps.PACKER_RECIPES.recipeBuilder()
        .inputs(definitions.materials().certusQuartzCrystal().maybeStack(4).get())
        .outputs(definitions.blocks().quartzBlock().maybeStack(1).get())
        .EUt(4).duration(100)
        .buildAndRegister()
RecipeMaps.PACKER_RECIPES.recipeBuilder()
        .inputs(definitions.materials().purifiedCertusQuartzCrystal().maybeStack(8).get())
        .outputs(definitions.blocks().quartzBlock().maybeStack(1).get())
        .EUt(4).duration(100)
        .buildAndRegister()
// fluix block
RecipeMaps.PACKER_RECIPES.recipeBuilder()
        .inputs(definitions.materials().fluixCrystal().maybeStack(4).get())
        .outputs(definitions.blocks().fluixBlock().maybeStack(1).get())
        .EUt(4).duration(100)
        .buildAndRegister()
RecipeMaps.PACKER_RECIPES.recipeBuilder()
        .inputs(definitions.materials().purifiedFluixCrystal().maybeStack(8).get())
        .outputs(definitions.blocks().fluixBlock().maybeStack(1).get())
        .EUt(4).duration(100)
        .buildAndRegister()
// sky stone
RecipeMaps.BLAST_RECIPES.recipeBuilder()
        .blastFurnaceTemp(900)
        .inputs(item('minecraft:stone'))
        .outputs(definitions.blocks().skyStoneBlock().maybeStack(1).get())
        .EUt(30).duration(40)
        .buildAndRegister()
// me security terminal
crafting.shapedBuilder()
        .row('PCP')
        .row('FSF')
        .row('PEP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Iron))
        .key('C', definitions.blocks().chest().maybeStack(1).get())
        .key('F', definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
        .key('S', definitions.materials().cell1kPart().maybeStack(1).get())
        .key('E', definitions.materials().engProcessor().maybeStack(1).get())
        .output(definitions.blocks().securityStation().maybeStack(1).get())
        .replace()
        .register()
// me quantum ring
crafting.shapedBuilder()
        .row('IGI')
        .row('ECS')
        .row('IGI')
        .key('I', OreDictUnifier.get(OrePrefix.ingot, Materials.Iron))
        .key('G', definitions.materials().logicProcessor().maybeStack(1).get())
        .key('E', definitions.materials().engProcessor().maybeStack(1).get())
        .key('C', definitions.blocks().energyCell().maybeStack(1).get())
        .key('S', definitions.materials().cell1kPart().maybeStack(1).get())
        .output(definitions.blocks().quantumRing().maybeStack(1).get())
        .replace()
        .register()
// me controller
crafting.removeByOutput(definitions.blocks().controller().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(0)
        .inputs(definitions.materials().purifiedFluixCrystal().maybeStack(4).get())
        .input(MetaTileEntities.HULL[GTValues.LV])
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV)
        .outputs(definitions.blocks().controller().maybeStack(1).get())
        .EUt(30).duration(300)
        .buildAndRegister()
// me drive
crafting.shapedBuilder()
        .row('HPH')
        .row('FEF')
        .row('HPH')
        .key('H', MetaTileEntities.HULL[GTValues.LV].getStackForm())
        .key('P', definitions.materials().engProcessor().maybeStack(1).get())
        .key('F', definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
        .key('E', MetaItems.EMITTER_LV.getStackForm())
        .output(definitions.blocks().drive().maybeStack(1).get())
        .replace()
        .register()
// me chest
crafting.shapedBuilder()
        .row('CHC')
        .row('HEH')
        .row('CHC')
        .key('C', item('actuallyadditions:block_giant_chest'))
        .key('H', MetaTileEntities.ITEM_IMPORT_BUS[GTValues.LV].getStackForm())
        .key('E', definitions.materials().engProcessor().maybeStack(1).get())
        .output(definitions.blocks().chest().maybeStack(1).get())
        .replace()
        .register()
// me interface
crafting.replaceShapeless(definitions.blocks().iface().maybeStack(1).get(), [definitions.parts().iface().maybeStack(1).get()])
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(4).get())
        .input(MetaItems.ELECTRIC_PISTON_LV, 4)
        .input(MetaTileEntities.HULL[GTValues.LV])
        .outputs(definitions.blocks().iface().maybeStack(2).get())
        .EUt(30).duration(150)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(2).get())
        .input(MetaItems.ELECTRIC_PISTON_HV, 2)
        .input(MetaTileEntities.HULL[GTValues.HV])
        .outputs(definitions.blocks().iface().maybeStack(4).get())
        .EUt(480).duration(150)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(1).get())
        .input(MetaItems.ELECTRIC_PISTON_IV)
        .input(MetaTileEntities.HULL[GTValues.IV])
        .outputs(definitions.blocks().iface().maybeStack(8).get())
        .EUt(7680).duration(150)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(1).get())
        .input(MetaItems.ELECTRIC_PISTON_ZPM)
        .input(MetaTileEntities.HULL[GTValues.ZPM])
        .outputs(definitions.blocks().iface().maybeStack(16).get())
        .EUt(122880).duration(150)
        .buildAndRegister()
// me fluid interface
crafting.replaceShapeless(definitions.blocks().fluidIface().maybeStack(1).get(), [definitions.parts().fluidIface().maybeStack(1).get()])
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(4).get())
        .input(MetaItems.ELECTRIC_PUMP_LV, 4)
        .input(MetaTileEntities.HULL[GTValues.LV])
        .outputs(definitions.blocks().fluidIface().maybeStack(2).get())
        .EUt(30).duration(150)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(2).get())
        .input(MetaItems.ELECTRIC_PUMP_HV, 2)
        .input(MetaTileEntities.HULL[GTValues.HV])
        .outputs(definitions.blocks().fluidIface().maybeStack(4).get())
        .EUt(480).duration(150)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(1).get())
        .input(MetaItems.ELECTRIC_PUMP_IV)
        .input(MetaTileEntities.HULL[GTValues.IV])
        .outputs(definitions.blocks().fluidIface().maybeStack(8).get())
        .EUt(7680).duration(150)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(1).get())
        .input(MetaItems.ELECTRIC_PUMP_ZPM)
        .input(MetaTileEntities.HULL[GTValues.ZPM])
        .outputs(definitions.blocks().fluidIface().maybeStack(16).get())
        .EUt(122880).duration(150)
        .buildAndRegister()
// molecular assembler
crafting.shapedBuilder()
        .row('TCT')
        .row('FHA')
        .row('TCT')
        .key('T', ore('workbench'))
        .key('C', ore('circuitLv'))
        .key('F', definitions.materials().formationCore().maybeStack(1).get())
        .key('H', MetaTileEntities.HULL[GTValues.LV].getStackForm())
        .key('A', definitions.materials().annihilationCore().maybeStack(1).get())
        .output(definitions.blocks().molecularAssembler().maybeStack(1).get())
        .replace()
        .register()
// certus quartz crystal
RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder()
        .input(OrePrefix.gem, Materials.CertusQuartz)
        .fluidInputs(Materials.Water.getFluid(250))
        .outputs(definitions.materials().certusQuartzCrystal().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder()
        .input(OrePrefix.gem, Materials.Quartzite)
        .fluidInputs(Materials.Water.getFluid(2000))
        .outputs(definitions.materials().certusQuartzCrystal().maybeStack(1).get())
        .EUt(120).duration(160)
        .buildAndRegister()
// charged certus quartz crystal
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .inputs(definitions.materials().certusQuartzCrystal().maybeStack(1).get())
        .input(OrePrefix.dust, Materials.Redstone)
        .outputs(definitions.materials().certusQuartzCrystalCharged().maybeStack(1).get())
        .EUt(30).duration(30)
        .buildAndRegister()
// certus quartz dust
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(definitions.materials().certusQuartzCrystal().maybeStack(1).get())
        .output(OrePrefix.dust, Materials.CertusQuartz)
        .EUt(30).duration(130)
        .buildAndRegister()
// fluix crystal
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .inputs(definitions.materials().certusQuartzCrystalCharged().maybeStack(1).get())
        .input(OrePrefix.dust, Materials.Redstone)
        .input(OrePrefix.dust, Materials.NetherQuartz)
        .outputs(definitions.materials().fluixCrystal().maybeStack(2).get())
        .EUt(30).duration(130)
        .buildAndRegister()
// fluix dust
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(definitions.materials().fluixCrystal().maybeStack(1).get())
        .outputs(definitions.materials().fluixDust().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
// pure certus quartz crystal
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.dust, Materials.CertusQuartz)
        .outputs(definitions.materials().purifiedCertusQuartzCrystal().maybeStack(2).get())
        .EUt(30).duration(120)
        .buildAndRegister()
// pure nether quartz crystal
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.dust, Materials.NetherQuartz)
        .outputs(definitions.materials().purifiedNetherQuartzCrystal().maybeStack(2).get())
        .EUt(30).duration(120)
        .buildAndRegister()
// pure fluix crystal
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .inputs(definitions.materials().fluixDust().maybeStack(1).get())
        .outputs(definitions.materials().purifiedFluixCrystal().maybeStack(2).get())
        .EUt(30).duration(120)
        .buildAndRegister()
// inscriber calculation press
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.plate, Materials.StainlessSteel)
        .outputs(definitions.materials().calcProcessorPress().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
// inscriber engineering press
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.Red)
        .input(OrePrefix.plate, Materials.StainlessSteel)
        .outputs(definitions.materials().engProcessorPress().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
// inscriber logic press
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.Red)
        .input(OrePrefix.plate, Materials.Aluminium)
        .outputs(definitions.materials().logicProcessorPress().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
// printed calculation circuit
mods.appliedenergistics2.inscriber.removeByOutput(definitions.materials().calcProcessorPrint().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .notConsumable(definitions.materials().calcProcessorPress().maybeStack(1).get())
        .inputs(definitions.materials().certusQuartzCrystal().maybeStack(1).get())
        .outputs(definitions.materials().calcProcessorPrint().maybeStack(1).get())
        .EUt(30).duration(300)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .notConsumable(definitions.materials().calcProcessorPress().maybeStack(1).get())
        .inputs(definitions.materials().purifiedCertusQuartzCrystal().maybeStack(1).get())
        .outputs(definitions.materials().calcProcessorPrint().maybeStack(1).get())
        .EUt(30).duration(300)
        .buildAndRegister()
// printed engineering circuit
mods.appliedenergistics2.inscriber.removeByOutput(definitions.materials().engProcessorPrint().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .notConsumable(definitions.materials().engProcessorPress().maybeStack(1).get())
        .input(OrePrefix.gem, Materials.Diamond)
        .outputs(definitions.materials().engProcessorPrint().maybeStack(1).get())
        .EUt(30).duration(300)
        .buildAndRegister()
// printed logic circuit
mods.appliedenergistics2.inscriber.removeByOutput(definitions.materials().logicProcessorPrint().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .notConsumable(definitions.materials().logicProcessorPress().maybeStack(1).get())
        .input(OrePrefix.ingot, Materials.Gold)
        .outputs(definitions.materials().logicProcessorPrint().maybeStack(1).get())
        .EUt(30).duration(300)
        .buildAndRegister()
// inscriber silicon press
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.plate, Materials.Aluminium)
        .outputs(definitions.materials().siliconPress().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
// printed silicon
mods.appliedenergistics2.inscriber.removeByOutput(definitions.materials().siliconPrint().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .notConsumable(definitions.materials().siliconPress().maybeStack(1).get())
        .input(OrePrefix.ingot, Materials.Silicon)
        .outputs(definitions.materials().siliconPrint().maybeStack(1).get())
        .EUt(30).duration(300)
        .buildAndRegister()
// logic processor
mods.appliedenergistics2.inscriber.removeByOutput(definitions.materials().logicProcessor().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.materials().logicProcessorPrint().maybeStack(1).get(), definitions.materials().siliconPrint().maybeStack(1).get())
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV)
        .fluidInputs(Materials.Polyethylene.getFluid(144))
        .outputs(definitions.materials().logicProcessor().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
// calculation processor
mods.appliedenergistics2.inscriber.removeByOutput(definitions.materials().calcProcessor().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.materials().calcProcessorPrint().maybeStack(1).get(), definitions.materials().siliconPrint().maybeStack(1).get())
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV)
        .fluidInputs(Materials.Polyethylene.getFluid(144))
        .outputs(definitions.materials().calcProcessor().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
// engineering processor
mods.appliedenergistics2.inscriber.removeByOutput(definitions.materials().engProcessor().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.materials().engProcessorPrint().maybeStack(1).get(), definitions.materials().siliconPrint().maybeStack(1).get())
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV)
        .fluidInputs(Materials.Polyethylene.getFluid(144))
        .outputs(definitions.materials().engProcessor().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
// 1k me storage component
crafting.removeByOutput(definitions.materials().cell1kPart().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .inputs(definitions.materials().certusQuartzCrystal().maybeStack(4).get())
        .input(OrePrefix.plate, Materials.Steel, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV)
        .outputs(definitions.materials().cell1kPart().maybeStack(1).get())
        .EUt(30).duration(300)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .inputs(definitions.materials().purifiedCertusQuartzCrystal().maybeStack(4).get())
        .input(OrePrefix.plate, Materials.Steel, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV)
        .outputs(definitions.materials().cell1kPart().maybeStack(1).get())
        .EUt(30).duration(300)
        .buildAndRegister()
// 4k me storage component
crafting.removeByOutput(definitions.materials().cell4kPart().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .inputs(definitions.materials().certusQuartzCrystal().maybeStack(4).get(), definitions.materials().cell1kPart().maybeStack(3).get())
        .input(OrePrefix.plate, Materials.Aluminium, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.MV)
        .outputs(definitions.materials().cell4kPart().maybeStack(1).get())
        .EUt(120).duration(300)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .inputs(definitions.materials().purifiedCertusQuartzCrystal().maybeStack(4).get(), definitions.materials().cell1kPart().maybeStack(3).get())
        .input(OrePrefix.plate, Materials.Aluminium, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.MV)
        .outputs(definitions.materials().cell4kPart().maybeStack(1).get())
        .EUt(120).duration(300)
        .buildAndRegister()
// 16k me storage component
crafting.removeByOutput(definitions.materials().cell16kPart().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .inputs(definitions.materials().certusQuartzCrystal().maybeStack(4).get(), definitions.materials().cell4kPart().maybeStack(3).get())
        .input(OrePrefix.plate, Materials.StainlessSteel, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.HV)
        .outputs(definitions.materials().cell16kPart().maybeStack(1).get())
        .EUt(480).duration(300)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .inputs(definitions.materials().purifiedCertusQuartzCrystal().maybeStack(4).get(), definitions.materials().cell4kPart().maybeStack(3).get())
        .input(OrePrefix.plate, Materials.StainlessSteel, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.HV)
        .outputs(definitions.materials().cell16kPart().maybeStack(1).get())
        .EUt(480).duration(300)
        .buildAndRegister()
// 64k me storage component
crafting.removeByOutput(definitions.materials().cell64kPart().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .inputs(definitions.materials().certusQuartzCrystal().maybeStack(4).get(), definitions.materials().cell16kPart().maybeStack(3).get())
        .input(OrePrefix.plate, Materials.Titanium, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.EV)
        .outputs(definitions.materials().cell64kPart().maybeStack(1).get())
        .EUt(1920).duration(300)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .inputs(definitions.materials().purifiedCertusQuartzCrystal().maybeStack(4).get(), definitions.materials().cell16kPart().maybeStack(3).get())
        .input(OrePrefix.plate, Materials.Titanium, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.EV)
        .outputs(definitions.materials().cell64kPart().maybeStack(1).get())
        .EUt(1920).duration(300)
        .buildAndRegister()
// sky stone dust
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().skyStoneBlock().maybeStack(1).get())
        .outputs(definitions.materials().skyDust().maybeStack(1).get())
        .EUt(28).duration(160)
        .buildAndRegister()
// blank pattern
crafting.removeByOutput(definitions.materials().blankPattern().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(4).get())
        .input(OrePrefix.plate, Materials.Steel, 2)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV)
        .fluidInputs(Materials.Polyethylene.getFluid(144))
        .outputs(definitions.materials().blankPattern().maybeStack(8).get())
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.blocks().quartzGlass().maybeStack(8).get())
        .input(OrePrefix.plate, Materials.Steel, 4)
        .input(GCYLCoreItems.MICRO_PROCESSOR)
        .fluidInputs(Materials.Polyethylene.getFluid(288))
        .outputs(definitions.materials().blankPattern().maybeStack(16).get())
        .EUt(120).duration(160)
        .buildAndRegister()
// 1k me fluid storage component
crafting.removeByOutput(definitions.materials().fluidCell1kPart().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.plate, Materials.Steel, 4)
        .input(OrePrefix.dye, MarkerMaterials.Color.Blue, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV)
        .outputs(definitions.materials().fluidCell1kPart().maybeStack(1).get())
        .EUt(30).duration(300)
        .buildAndRegister()
// 4k me fluid storage component
crafting.removeByOutput(definitions.materials().fluidCell4kPart().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .inputs(definitions.materials().fluidCell1kPart().maybeStack(3).get())
        .input(OrePrefix.plate, Materials.Aluminium, 4)
        .input(OrePrefix.dye, MarkerMaterials.Color.Blue, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.MV)
        .outputs(definitions.materials().fluidCell4kPart().maybeStack(1).get())
        .EUt(120).duration(300)
        .buildAndRegister()
// 16k me fluid storage component
crafting.removeByOutput(definitions.materials().fluidCell16kPart().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .inputs(definitions.materials().fluidCell4kPart().maybeStack(3).get())
        .input(OrePrefix.plate, Materials.StainlessSteel, 4)
        .input(OrePrefix.dye, MarkerMaterials.Color.Blue, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.HV)
        .outputs(definitions.materials().fluidCell16kPart().maybeStack(1).get())
        .EUt(480).duration(300)
        .buildAndRegister()
// 64k me fluid storage component
crafting.removeByOutput(definitions.materials().fluidCell64kPart().maybeStack(1).get())
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .inputs(definitions.materials().fluidCell16kPart().maybeStack(3).get())
        .input(OrePrefix.plate, Materials.Titanium, 4)
        .input(OrePrefix.dye, MarkerMaterials.Color.Blue, 4)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.EV)
        .outputs(definitions.materials().fluidCell64kPart().maybeStack(1).get())
        .EUt(1920).duration(300)
        .buildAndRegister()
// quantum link card
crafting.shapedBuilder()
        .row('DWD')
        .row('SFE')
        .row('DCD')
        .key('D', OreDictUnifier.get(OrePrefix.plateDouble, TJMaterials.StarMetalAlloy))
        .key('W', definitions.materials().wirelessReceiver().maybeStack(1).get())
        .key('S', MetaItems.SENSOR_IV.getStackForm())
        .key('F', MetaItems.FIELD_GENERATOR_IV.getStackForm())
        .key('E', MetaItems.EMITTER_IV.getStackForm())
        .key('C', OreDictUnifier.get(OrePrefix.plate, GCYLNuclearMaterials.Curium247))
        .output(definitions.materials().cardQuantumLink().maybeStack(1).get())
        .replace()
        .register()
// quartz fiber
crafting.removeByOutput(definitions.parts().quartzFiber().maybeStack(1).get())
RecipeMaps.WIREMILL_RECIPES.recipeBuilder()
        .inputs(definitions.materials().purifiedNetherQuartzCrystal().maybeStack(1).get())
        .outputs(definitions.parts().quartzFiber().maybeStack(6).get())
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.WIREMILL_RECIPES.recipeBuilder()
        .input(OrePrefix.gem, Materials.NetherQuartz)
        .outputs(definitions.parts().quartzFiber().maybeStack(1).get())
        .EUt(30).duration(160)
        .buildAndRegister()
// me glass cable
for (i in 0..<Materials.CHEMICAL_DYES.length) {
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
            .fluidInputs(Materials.CHEMICAL_DYES[i].getFluid(18))
            .outputs(definitions.parts().cableGlass().stack(AEColor.values()[i], 1))
            .EUt(7).duration(20)
            .buildAndRegister()
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableGlass().stack(AEColor.values()[i], 1))
            .fluidInputs(Materials.Water.getFluid(250))
            .outputs(definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
            .EUt(7).duration(20)
            .buildAndRegister()
}
// me covered cable
for (i in 0..<Materials.CHEMICAL_DYES.length) {
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 1))
            .fluidInputs(Materials.CHEMICAL_DYES[i].getFluid(18))
            .outputs(definitions.parts().cableCovered().stack(AEColor.values()[i], 1))
            .EUt(7).duration(20)
            .buildAndRegister()
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableCovered().stack(AEColor.values()[i], 1))
            .fluidInputs(Materials.Water.getFluid(250))
            .outputs(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 1))
            .EUt(7).duration(20)
            .buildAndRegister()
}
crafting.removeByOutput(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 1))
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
        .input(OrePrefix.foil, Materials.Rubber, 4)
        .outputs(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 4))
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
        .input(OrePrefix.foil, Materials.Polyethylene, 2)
        .outputs(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 4))
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
        .input(OrePrefix.foil, Materials.PolyphenyleneSulfide)
        .outputs(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 4))
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
        .input(OrePrefix.foil, Materials.Polybenzimidazole)
        .outputs(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 6))
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
        .input(OrePrefix.foil, GCYLMaterials.Polyetheretherketone)
        .outputs(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 8))
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
        .input(OrePrefix.foil, GCYLMaterials.Zylon)
        .outputs(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 16))
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(definitions.parts().cableGlass().stack(AEColor.TRANSPARENT, 1))
        .input(OrePrefix.foil, GCYLMaterials.FullerenePolymerMatrix)
        .outputs(definitions.parts().cableCovered().stack(AEColor.TRANSPARENT, 32))
        .EUt(30).duration(160)
        .buildAndRegister()
// creative energy cell
RecipeMaps.ASSEMBLY_LINE_RECIPES.recipeBuilder()
        .inputs(item('appliedenergistics2:dense_energy_cell') * 64)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.UVSuperconductor, 32)
        .input(OrePrefix.plate, GCYLMaterials.EnrichedNaquadahAlloy, 8)
        .input(OrePrefix.plateDense, GCYLMaterials.Draconium, 7)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.UV, 2)
        .fluidInputs(Materials.Tritanium.getFluid(720), Materials.SolderingAlloy.getFluid(1296))
        .outputs(definitions.blocks().energyCellCreative().maybeStack(1).get())
        .EUt(GTValues.V[GTValues.UV]).duration(1000)
        .buildAndRegister()
// me smart cable
for (i in 0..<Materials.CHEMICAL_DYES.length) {
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableSmart().stack(AEColor.TRANSPARENT, 1))
            .fluidInputs(Materials.CHEMICAL_DYES[i].getFluid(18))
            .outputs(definitions.parts().cableSmart().stack(AEColor.values()[i], 1))
            .EUt(7).duration(20)
            .buildAndRegister()
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableSmart().stack(AEColor.values()[i], 1))
            .fluidInputs(Materials.Water.getFluid(250))
            .outputs(definitions.parts().cableSmart().stack(AEColor.TRANSPARENT, 1))
            .EUt(7).duration(20)
            .buildAndRegister()
}
// me dense smart cable
for (i in 0..<Materials.CHEMICAL_DYES.length) {
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableDenseSmart().stack(AEColor.TRANSPARENT, 1))
            .fluidInputs(Materials.CHEMICAL_DYES[i].getFluid(18))
            .outputs(definitions.parts().cableDenseSmart().stack(AEColor.values()[i], 1))
            .EUt(7).duration(20)
            .buildAndRegister()
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableDenseSmart().stack(AEColor.values()[i], 1))
            .fluidInputs(Materials.Water.getFluid(250))
            .outputs(definitions.parts().cableDenseSmart().stack(AEColor.TRANSPARENT, 1))
            .EUt(7).duration(20)
            .buildAndRegister()
}
// me dense covered cable
for (i in 0..<Materials.CHEMICAL_DYES.length) {
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableDenseCovered().stack(AEColor.TRANSPARENT, 1))
            .fluidInputs(Materials.CHEMICAL_DYES[i].getFluid(18))
            .outputs(definitions.parts().cableDenseCovered().stack(AEColor.values()[i], 1))
            .EUt(7).duration(20)
            .buildAndRegister()
    RecipeMaps.CHEMICAL_BATH_RECIPES.recipeBuilder()
            .inputs(definitions.parts().cableDenseCovered().stack(AEColor.values()[i], 1))
            .fluidInputs(Materials.Water.getFluid(250))
            .outputs(definitions.parts().cableDenseCovered().stack(AEColor.TRANSPARENT, 1))
            .EUt(7).duration(20)
            .buildAndRegister()
}
// me oredict storage bus
crafting.replaceShapeless(definitions.parts().oreDictStorageBus().maybeStack(1).get(), [MetaItems.ITEM_FILTER.getStackForm(),
                                                                                        definitions.parts().storageBus().maybeStack(1).get()])