import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.blocks.BlockGlassCasing
import gregtech.common.blocks.MetaBlocks
import gregtech.common.items.MetaItems
import gregtech.common.metatileentities.MetaTileEntities
import tja.blocks.BlockTieredGlass
import tja.blocks.TJAMetaBlocks

// bonsai pot
crafting.shapedBuilder()
        .row('   ')
        .row('P P')
        .row('PPP')
        .key('P', OreDictUnifier.get(OrePrefix.plateDouble, Materials.TungstenSteel))
        .output(item('bonsaitrees:bonsaipot'))
        .replace()
        .register()
// memory card (items) 10 B
crafting.shapedBuilder()
        .row('   ')
        .row('PCP')
        .row('PHP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('circuitIv'))
        .key('H', MetaTileEntities.HULL[GTValues.IV].getStackForm())
        .output(item('enderutilities:enderpart', 53))
        .replace()
        .register()
// warp core
crafting.shapedBuilder()
        .row('TCT')
        .row('THT')
        .row('TCT')
        .key('T', OreDictUnifier.get(OrePrefix.plate, Materials.Titanium))
        .key('C', ore('circuitEv'))
        .key('H', MetaTileEntities.HULL[GTValues.EV].getStackForm())
        .output(item('advancedrocketry:warpcore'))
        .replace()
        .register()
// super high pressure tank
RecipeMaps.EXTRUDER_RECIPES.recipeBuilder()
        .notConsumable(MetaItems.SHAPE_MOLD_CYLINDER)
        .input(OrePrefix.ingot, Materials.Titanium, 16)
        .outputs(item('advancedrocketry:pressuretank', 3))
        .EUt(1048).duration(600)
        .buildAndRegister()
// reinforced glass
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:hotturf') * 10)
        .input(OrePrefix.block, Materials.Glass)
        .outputs(MetaBlocks.TRANSPARENT_CASING.getItemVariant(BlockGlassCasing.CasingType.LAMINATED_GLASS)) // TODO replace with reinforced glass
        .EUt(2040).duration(300)
        .buildAndRegister()
// ender capacitor (advanced)
crafting.shapedBuilder()
        .row(' E ')
        .row('SCS')
        .row('OSO')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderPearl))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', ore('circuitHv'))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:endercapacitor', 2))
        .replace()
        .register()
// inactive ender core (advanced)
crafting.shapedBuilder()
        .row('OSO')
        .row('SCS')
        .row('OSO')
        .key('O', ore('obsidian'))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', ore('circuitHv'))
        .output(item('enderutilities:enderpart', 12))
        .replace()
        .register()
// creative breaking module
crafting.shapedBuilder()
        .row('SNS')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('N', OreDictUnifier.get(OrePrefix.gem, Materials.NetherStar))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:enderpart', 30))
        .replace()
        .register()
// wand of the lazy builder
crafting.shapedBuilder()
        .row('C  ')
        .row(' E ')
        .row('  E')
        .key('C', item('enderutilities:enderpart', 17))
        .key('E', item('enderio:item_alloy_ingot', 8))
        .output(item('enderutilities:builderswand'))
        .replace()
        .register()
// advanced ender porter
crafting.shapedBuilder()
        .row('ESE')
        .row('SCS')
        .row('ESE')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderEye))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', item('enderutilities:enderpart', 17))
        .output(item('enderutilities:enderporter', 1))
        .replace()
        .register()
// ender sword
crafting.shapedBuilder()
        .row(' S ')
        .row(' S ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endersword'))
        .replace()
        .register()
// ender pickaxe
crafting.shapedBuilder()
        .row('SSS')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool'))
        .replace()
        .register()
// ender axe
crafting.shapedBuilder()
        .row('SS ')
        .row('SE ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool', 1))
        .replace()
        .register()
// ender shovel
crafting.shapedBuilder()
        .row(' S ')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool', 2))
        .replace()
        .register()
// ender hoe
crafting.shapedBuilder()
        .row('SS ')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool', 3))
        .replace()
        .register()
// living matter manipulator
crafting.shapedBuilder()
        .row('VVV')
        .row('SCV')
        .row('  V')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', item('enderutilities:enderpart', 11))
        .output(item('enderutilities:livingmanipulator'))
        .replace()
        .register()
// portal scaler
crafting.shapedBuilder()
        .row('OGO')
        .row('OCO')
        .row('OSO')
        .key('O', ore('obsidian'))
        .key('G', ore('blockGlassPurple'))
        .key('C', item('enderutilities:enderpart', 17))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .output(item('enderutilities:portalscaler'))
        .replace()
        .register()
// void pickaxe
crafting.shapedBuilder()
        .row('SSS')
        .row('LEL')
        .row('FEF')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('L', item('minecraft:lava_bucket'))
        .key('E', item('enderutilities:enderpart', 20))
        .key('F', item('minecraft:fire_charge'))
        .output(item('enderutilities:void_pickaxe'))
        .replace()
        .register()
// energy bridge receiver
crafting.shapedBuilder()
        .row('SGS')
        .row('GCG')
        .row('SGS')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('G', ore('blockGlass'))
        .key('C', item('enderutilities:enderpart', 17))
        .output(item('enderutilities:energy_bridge', 1))
        .replace()
        .register()
// energy bridge transmitter
crafting.shapedBuilder()
        .row('SNS')
        .row('SCS')
        .row('SGS')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('N', OreDictUnifier.get(OrePrefix.gem, Materials.NetherStar))
        .key('C', item('enderutilities:enderpart', 17))
        .key('G', ore('blockGlass'))
        .output(item('enderutilities:energy_bridge', 2))
        .replace()
        .register()
// massive storage unit
crafting.shapedBuilder()
        .row('SHS')
        .row('SCS')
        .row('SHS')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('H', item('enderutilities:storage_0', 5))
        .key('C', item('enderutilities:enderpart', 17))
        .output(item('enderutilities:msu'))
        .replace()
        .register()
// end steel ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_alloy_ingot'))
        .input(OrePrefix.gem, Materials.EnderEye)
        .outputs(item('enderio:item_alloy_ingot', 8))
        .EUt(1024).duration(160)
        .buildAndRegister()
// ruined marble
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blockmarble', 6))
crafting.shapedBuilder()
        .row('FMF')
        .row('MPM')
        .row('FMF')
        .key('F', OreDictUnifier.get(OrePrefix.foil, Materials.Tungsten))
        .key('M', ore('stoneMarble'))
        .key('P', OreDictUnifier.get(OrePrefix.wireFine, Materials.Platinum))
        .output(item('astralsorcery:blockmarble', 6))
        .replace()
        .register()
// starmetal ingot
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:itemcraftingcomponent', 1))
// block of starmetal
mods.astralsorcery.starlight_altar.removeByOutput(item('astraladditions:block_starmetal'))
// stardust
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('astralsorcery:blockcustomore', 1))
        .outputs(item('astralsorcery:itemcraftingcomponent', 2) * 2)
        .EUt(12).duration(20)
        .buildAndRegister()
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('astralsorcery:itemcraftingcomponent', 1))
        .outputs(item('astralsorcery:itemcraftingcomponent', 2))
        .EUt(128).duration(30)
        .buildAndRegister()
// illumination powder
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.dust, Materials.Glowstone, 4)
        .input('gemAquamarine')
        .outputs(item('astralsorcery:itemusabledust') * 16)
        .EUt(800).duration(30)
        .buildAndRegister()
// nocturnal powder
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.dust, Materials.Carbon, 3)
        .input(OrePrefix.gem, Materials.Lapis)
        .inputs(item('astralsorcery:itemusabledust'))
        .outputs(item('astralsorcery:itemusabledust', 1) * 4)
        .EUt(1150).duration(30)
        .buildAndRegister()
// light well
mods.astralsorcery.lightwell.removeByOutput(Materials.Water.getFluid(1))
mods.astralsorcery.lightwell.removeByOutput(Materials.Lava.getFluid(1))
mods.astralsorcery.lightwell.recipeBuilder()
        .catalyst(item('randomthings:ingredient', 2))
        .output(fluid('astralsorcery.liquidstarlight') * 1000)
        .productionMultiplier(20.0F)
        .shatterMultiplier(1000.0F)
        .register()
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blockwell'))
mods.astralsorcery.starlight_altar.discoveryRecipeBuilder()
        .row('RAR')
        .row('DTD')
        .row('ROR')
        .key('R', item('astralsorcery:blockmarble', 6))
        .key('A', ore('gemAquamarine'))
        .key('D', OreDictUnifier.get(OrePrefix.plateDense, Materials.Ruthenium))
        .key('T', MetaBlocks.TRANSPARENT_CASING.getItemVariant(BlockGlassCasing.CasingType.LAMINATED_GLASS)) // TODO replace with tungsten reinforced glass
        .key('O', OreDictUnifier.get(OrePrefix.plateDense, Materials.Osmium))
        .output(item('astralsorcery:blockwell'))
        .starlight(700)
        .craftTime(300)
        .register()
// starlight crafting altar
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blockaltar', 1))
mods.astralsorcery.starlight_altar.discoveryRecipeBuilder()
        .row('MRM')
        .row('UDU')
        .row('MDM')
        .key('M', ore('stoneMarble'))
        .key('R', item('astralsorcery:itemrockcrystalsimple').or(item('astralsorcery:itemtunedcelestialcrystal')))
        .key('U', item('astralsorcery:blockmarble', 6))
        .key('D', OreDictUnifier.get(OrePrefix.plateDouble, Materials.TungstenSteel))
        .output(item('astralsorcery:blockaltar', 1))
        .starlight(200)
        .craftTime(300)
        .register()
// glass lens
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:itemcraftingcomponent', 3))
mods.astralsorcery.starlight_altar.discoveryRecipeBuilder()
        .row(' L ')
        .row('LAL')
        .row(' L ')
        .key('L', OreDictUnifier.get(OrePrefix.lens, Materials.NetherStar))
        .key('A', ore('gemAquamarine'))
        .output(item('astralsorcery:itemcraftingcomponent', 3))
        .starlight(5)
        .craftTime(300)
        .register()
// cave illuminator
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blockworldilluminator'))
mods.astralsorcery.starlight_altar.discoveryRecipeBuilder()
        .row('IAI')
        .row('A A')
        .row('IAI')
        .key('I', item('astralsorcery:itemusabledust'))
        .key('A', ore('gemAquamarine'))
        .output(item('astralsorcery:blockworldilluminator'))
        .starlight(200)
        .craftTime(300)
        .register()
// linking tool
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:itemlinkingtool'))
mods.astralsorcery.starlight_altar.discoveryRecipeBuilder()
        .row('SAR')
        .row('SLA')
        .row('LSS')
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.Wood))
        .key('A', ore('gemAquamarine'))
        .key('R', item('astralsorcery:itemrockcrystalsimple').or(item('astralsorcery:itemtunedcelestialcrystal')))
        .key('L', ore('logWood'))
        .output(item('astralsorcery:itemlinkingtool'))
        .starlight(5)
        .craftTime(300)
        .register()
// diamond /dank/null panel
crafting.shapedBuilder()
        .row('DCD')
        .row('CGC')
        .row('DCD')
        .key('D', ore('blockDiamond'))
        .key('C', ore('blockFuelCoke'))
        .key('G', TJAMetaBlocks.TIERED_GLASS.getItemVariant(BlockTieredGlass.CasingType.EV))
        .output(item('danknull:dank_null_panel_4'))
        .replace()
        .register()
// /dev/null/MK V
crafting.shapedBuilder()
        .row('PPP')
        .row('PDP')
        .row('PPP')
        .key('P', item('danknull:dank_null_panel_4'))
        .key('D', item('danknull:dank_null_3'))
        .output(item('danknull:dank_null_4'))
        .replace()
        .register()