import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.MarkerMaterials
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.items.MetaItems
import gregtech.common.metatileentities.MetaTileEntities
import tja.blocks.BlockTieredGlass
import tja.blocks.TJAMetaBlocks

// handy bag
crafting.shapedBuilder()
        .row('PBP')
        .row('BCB')
        .row('PBP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('B', item('retro_sophisticated_backpacks:backpack_obsidian'))
        .key('C', ore('circuitHv'))
        .output(item('enderutilities:handybag'))
        .replace()
        .register()
// memory card (items) 6 B
crafting.removeByOutput(item('enderutilities:enderpart', 51))
crafting.shapedBuilder()
        .row('   ')
        .row('PCP')
        .row('PBP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('circuitHv'))
        .key('B', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('enderutilities:enderpart', 51))
        .register()
// launch pad
crafting.removeByOutput(item('advancedrocketry:launchpad'))
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .input(OrePrefix.block, Materials.Concrete, 3)
        .input(OrePrefix.dye, MarkerMaterials.Color.Yellow)
        .input(OrePrefix.dye, MarkerMaterials.Color.Black)
        .outputs(item('advancedrocketry:launchpad') * 3)
        .EUt(16).duration(240)
        .buildAndRegister()
// space helmet
crafting.shapedBuilder()
        .row('WPW')
        .row('WLW')
        .row('PSP')
        .key('W', ore('wool'))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('L', OreDictUnifier.get(OrePrefix.craftingLens, MarkerMaterials.Color.White))
        .key('S', item('minecraft:leather_helmet'))
        .output(item('advancedrocketry:spacehelmet'))
        .replace()
        .register()
// space suit chest-piece
crafting.shapedBuilder()
        .row(' P ')
        .row('WSW')
        .row('PWP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('W', ore('wool'))
        .key('S', item('minecraft:leather_chestplate'))
        .output(item('advancedrocketry:spacechestplate'))
        .replace()
        .register()
// space suit leggings
crafting.shapedBuilder()
        .row('PWP')
        .row('WSW')
        .row('W W')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('W', ore('wool'))
        .key('S', item('minecraft:leather_leggings'))
        .output(item('advancedrocketry:spaceleggings'))
        .replace()
        .register()
// space boots
crafting.shapedBuilder()
        .row('PWP')
        .row('WSW')
        .row('PWP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('W', ore('wool'))
        .key('S', item('minecraft:leather_boots'))
        .output(item('advancedrocketry:spaceboots'))
        .replace()
        .register()
// holo-projector
crafting.shapedBuilder()
        .row('GEG')
        .row(' H ')
        .row('   ')
        .key('G', ore('paneGlass'))
        .key('E', MetaItems.EMITTER_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('libvulpes:holoprojector'))
        .replace()
        .register()
// gas charge pad
crafting.shapedBuilder()
        .row('   ')
        .row('SPS')
        .row(' D ')
        .key('S', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('P', MetaItems.ELECTRIC_PUMP_HV.getStackForm())
        .key('D', MetaTileEntities.BRONZE_DRUM.getStackForm())
        .output(item('advancedrocketry:oxygencharger'))
        .replace()
        .register()
// fueling station
crafting.shapedBuilder()
        .row('SPS')
        .row('PHP')
        .row('SPS')
        .key('S', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('P', MetaItems.ELECTRIC_PUMP_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('advancedrocketry:fuelingstation'))
        .replace()
        .register()
// rocket assembling machine
crafting.shapedBuilder()
        .row('TUT')
        .row('RHR')
        .row('T T')
        .key('T', OreDictUnifier.get(OrePrefix.plate, Materials.Titanium))
        .key('U', item('advancedrocketry:misc'))
        .key('R', MetaItems.ROBOT_ARM_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('advancedrocketry:rocketbuilder'))
        .replace()
        .register()
// guidance computer
crafting.shapedBuilder()
        .row('IUI')
        .row('EHE')
        .row('ISI')
        .key('I', OreDictUnifier.get(OrePrefix.plate, Materials.Iron))
        .key('U', item('advancedrocketry:misc'))
        .key('E', MetaItems.EMITTER_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .key('S', MetaItems.SENSOR_HV.getStackForm())
        .output(item('advancedrocketry:guidancecomputer'))
        .replace()
        .register()
// orientation controller
crafting.shapedBuilder()
        .row('PHP')
        .row('HSH')
        .row('PHP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .key('S', item('advancedrocketry:misc'))
        .output(item('advancedrocketry:orientationcontroller'))
        .replace()
        .register()
// satellite bay
crafting.shapedBuilder()
        .row('RPR')
        .row('PCP')
        .row('RPR')
        .key('R', OreDictUnifier.get(OrePrefix.stick, Materials.StainlessSteel))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('C', ore('chestWood'))
        .output(item('advancedrocketry:loader', 1))
        .replace()
        .register()
// oxygen vent
crafting.shapedBuilder()
        .row(' P ')
        .row(' H ')
        .row('SSS')
        .key('P', MetaItems.ELECTRIC_PUMP_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .key('S', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .output(item('advancedrocketry:oxygenvent'))
        .replace()
        .register()
// CO2 scrubber
crafting.shapedBuilder()
        .row('SSS')
        .row(' H ')
        .row(' P ')
        .key('P', MetaItems.ELECTRIC_PUMP_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .key('S', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .output(item('advancedrocketry:oxygenscrubber'))
        .replace()
        .register()
// station gravity controller
crafting.shapedBuilder()
        .row('PEP')
        .row('PHP')
        .row('PSP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('E', MetaItems.EMITTER_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .key('S', MetaItems.SENSOR_HV.getStackForm())
        .output(item('advancedrocketry:gravitycontroller'))
        .replace()
        .register()
// machine structure
crafting.shapedBuilder()
        .row('SPS')
        .row('PSP')
        .row('SPS')
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.StainlessSteel))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .output(item('libvulpes:structuremachine') * 4)
        .replace()
        .register()
// altitude controller
crafting.shapedBuilder()
        .row('PUP')
        .row('SHS')
        .row('PPP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('U', item('advancedrocketry:misc'))
        .key('S', MetaItems.SENSOR_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('advancedrocketry:altitudecontroller'))
        .replace()
        .register()
// station docking port
crafting.shapedBuilder()
        .row('PUP')
        .row('PHP')
        .row('PPP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('U', item('advancedrocketry:misc'))
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('advancedrocketry:stationmarker'))
        .replace()
        .register()
// area gravity controller
crafting.shapedBuilder()
        .row('SUS')
        .row('PHP')
        .row('PSP')
        .key('S', MetaItems.EMITTER_HV.getStackForm())
        .key('U', item('advancedrocketry:misc'))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('advancedrocketry:gravitymachine'))
        .replace()
        .register()
// space station assembler
crafting.shapedBuilder()
        .row('SPS')
        .row('RHR')
        .row('PEP')
        .key('S', MetaItems.SENSOR_HV.getStackForm())
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('R', MetaItems.ROBOT_ARM_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .key('E', MetaItems.EMITTER_HV.getStackForm())
        .output(item('advancedrocketry:stationbuilder'))
        .replace()
        .register()
// liquid fueled engine
crafting.shapedBuilder()
        .row(' S ')
        .row('S S')
        .row('PPP')
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.Steel))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .output(item('advancedrocketry:rocketmotor'))
        .replace()
        .register()
// advanced rocket engine
crafting.shapedBuilder()
        .row(' S ')
        .row('S S')
        .row('TTT')
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.StainlessSteel))
        .key('T', OreDictUnifier.get(OrePrefix.plate, Materials.Titanium))
        .output(item('advancedrocketry:advrocketmotor'))
        .replace()
        .register()
// liquid fuel tank
crafting.shapedBuilder()
        .row('SPS')
        .row('P P')
        .row('SPS')
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.StainlessSteel))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .output(item('advancedrocketry:fueltank') * 2)
        .replace()
        .register()
// satellite id chip
crafting.shapedBuilder()
        .row('   ')
        .row(' A ')
        .row('BBB')
        .key('A', item('advancedrocketry:ic', 2))
        .key('B', item('advancedrocketry:ic'))
        .output(item('advancedrocketry:satelliteidchip'))
        .replace()
        .register()
// silicon wafer
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('minecraft:glass_pane'))
        .input(MetaItems.SILICON_WAFER)
        .outputs(item('advancedrocketry:wafer'))
        .EUt(30).duration(160)
        .buildAndRegister()
// basic circuit plate
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .inputs(item('advancedrocketry:wafer'))
        .outputs(item('advancedrocketry:itemcircuitplate'))
        .EUt(30).duration(160)
        .buildAndRegister()
// advanced circuit plate
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.Lime)
        .inputs(item('advancedrocketry:wafer'))
        .outputs(item('advancedrocketry:itemcircuitplate', 1))
        .EUt(30).duration(160)
        .buildAndRegister()
// basic circuit
RecipeMaps.CUTTER_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:itemcircuitplate'))
        .fluidInputs(Materials.Lubricant.getFluid(144))
        .outputs(item('advancedrocketry:ic') * 16)
        .EUt(30).duration(160)
        .buildAndRegister()
// advanced circuit
RecipeMaps.CUTTER_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:itemcircuitplate', 1))
        .fluidInputs(Materials.Lubricant.getFluid(144))
        .outputs(item('advancedrocketry:ic', 2) * 16)
        .EUt(30).duration(160)
        .buildAndRegister()
// thermite
crafting.removeByOutput(item('advancedrocketry:thermite'))
RecipeMaps.CHEMICAL_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.Iron, 2)
        .input(OrePrefix.dust, Materials.Aluminium)
        .fluidInputs(Materials.Oxygen.getFluid(2000))
        .outputs(item('advancedrocketry:thermite') * 3)
        .EUt(30).duration(600)
        .buildAndRegister()
// airtight seal
crafting.shapedBuilder()
        .row(' S ')
        .row(' P ')
        .row(' B ')
        .key('S', OreDictUnifier.get(OrePrefix.stickLong, Materials.StainlessSteel))
        .key('P', item('advancedrocketry:spacehelmet').or(item('advancedrocketry:spacechestplate')).or(item('advancedrocketry:spaceleggings')
                .or(item('advancedrocketry:spaceboots'))))
        .key('B', item('minecraft:book'))
        .output(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['id': (short) 13, 'lvl': (short) 1]]]))
        .register()
// blue crystal shard
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:crystal'))
        .outputs(item('actuallyadditions:item_crystal_shard', 1) * 4)
        .EUt(30).duration(160)
        .buildAndRegister()
// light blue crystal shard
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:crystal', 1))
        .outputs(item('actuallyadditions:item_crystal_shard', 2) * 4)
        .EUt(30).duration(160)
        .buildAndRegister()
// green crystal shard
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:crystal', 2))
        .outputs(item('actuallyadditions:item_crystal_shard', 4) * 4)
        .EUt(30).duration(160)
        .buildAndRegister()
// red crystal shard
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:crystal', 3))
        .outputs(item('actuallyadditions:item_crystal_shard') * 4)
        .EUt(30).duration(160)
        .buildAndRegister()
// white crystal shard
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:crystal', 4))
        .outputs(item('actuallyadditions:item_crystal_shard', 5) * 4)
        .EUt(30).duration(160)
        .buildAndRegister()
// black crystal shard
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:crystal', 5))
        .outputs(item('actuallyadditions:item_crystal_shard', 3) * 4)
        .EUt(30).duration(160)
        .buildAndRegister()
// dilithium dust
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('libvulpes:ore0'))
        .outputs(item('libvulpes:productdust') * 2)
        .EUt(17).duration(120)
        .buildAndRegister()
// dilithium crystal
RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder()
        .inputs(item('libvulpes:productdust'))
        .fluidInputs(Materials.Water.getFluid(1000))
        .outputs(item('libvulpes:productgem'))
        .EUt(500).duration(120)
        .buildAndRegister()
// low pressure tank
RecipeMaps.EXTRUDER_RECIPES.recipeBuilder()
        .notConsumable(MetaItems.SHAPE_MOLD_CYLINDER)
        .input(OrePrefix.ingot, Materials.Iron, 16)
        .outputs(item('advancedrocketry:pressuretank'))
        .EUt(30).duration(600)
        .buildAndRegister()
// pressure tank
RecipeMaps.EXTRUDER_RECIPES.recipeBuilder()
        .notConsumable(MetaItems.SHAPE_MOLD_CYLINDER)
        .input(OrePrefix.ingot, Materials.Steel, 16)
        .outputs(item('advancedrocketry:pressuretank', 1))
        .EUt(120).duration(600)
        .buildAndRegister()
// high pressure tank
RecipeMaps.EXTRUDER_RECIPES.recipeBuilder()
        .notConsumable(MetaItems.SHAPE_MOLD_CYLINDER)
        .input(OrePrefix.ingot, Materials.StainlessSteel, 16)
        .outputs(item('advancedrocketry:pressuretank', 2))
        .EUt(500).duration(600)
        .buildAndRegister()
// large memory chest
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row(' H ')
        .key('C', ore('circuitIv'))
        .key('H', item('enderutilities:storage_0', 1))
        .output(item('enderutilities:storage_0', 2))
        .replace()
        .register()
// handy chest (large)
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row(' C ')
        .key('C', ore('circuitIv'))
        .key('H', item('enderutilities:storage_0', 4))
        .output(item('enderutilities:storage_0', 5))
        .replace()
        .register()
// conduit binder composite
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .inputs(item('minecraft:gravel') * 4)
        .input('sand', 4)
        .fluidInputs(Materials.Water.getFluid(1000))
        .outputs(item('enderio:item_material', 22) * 16)
        .EUt(500).duration(80)
        .buildAndRegister()
// telepad block
crafting.removeByOutput(item('enderio:block_tele_pad'))
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
    .inputs(item('enderio:block_cap_bank', 3))
    .input(MetaTileEntities.HULL[GTValues.MV], 3)
    .input(MetaItems.EMITTER_MV)
    .input(MetaItems.SENSOR_MV)
    .outputs(item('enderio:block_tele_pad') * 9)
    .EUt(480).duration(180)
    .buildAndRegister()
// electrum blend
crafting.removeByOutput(item('thermalfoundation:material', 97))
// invar blend
crafting.removeByOutput(item('thermalfoundation:material', 98))
// bronze blend
crafting.removeByOutput(item('thermalfoundation:material', 99))
// constantan blend
crafting.removeByOutput(item('thermalfoundation:material', 100))
// signalum blend
crafting.removeByOutput(item('thermalfoundation:material', 101))
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.Copper, 3)
        .input(OrePrefix.dust, Materials.Tin)
        .fluidInputs(Materials.Redstone.getFluid(1000))
        .outputs(item('thermalfoundation:material', 101) * 4)
        .EUt(500).duration(240)
        .buildAndRegister()
// lumium blend
crafting.removeByOutput(item('thermalfoundation:material', 102))
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.Tin, 3)
        .input(OrePrefix.dust, Materials.Silver)
        .fluidInputs(Materials.Glowstone.getFluid(1000))
        .outputs(item('thermalfoundation:material', 102) * 4)
        .EUt(500).duration(240)
        .buildAndRegister()
// enderium blend
crafting.removeByOutput(item('thermalfoundation:material', 103))
// signalum ingot
furnace.removeByOutput(item('thermalfoundation:material', 165))
RecipeMaps.BLAST_RECIPES.recipeBuilder()
        .blastFurnaceTemp(4500)
        .inputs(item('thermalfoundation:material', 101))
        .outputs(item('thermalfoundation:material', 165))
        .EUt(1920).duration(1530)
        .buildAndRegister()
// lumium ingot
furnace.removeByOutput(item('thermalfoundation:material', 166))
RecipeMaps.BLAST_RECIPES.recipeBuilder()
        .blastFurnaceTemp(4500)
        .inputs(item('thermalfoundation:material', 102))
        .outputs(item('thermalfoundation:material', 166))
        .EUt(1920).duration(1530)
        .buildAndRegister()
// gold /dank/null panel
crafting.shapedBuilder()
        .row('BCB')
        .row('CGC')
        .row('BCB')
        .key('B', ore('blockGold'))
        .key('C', ore('blockFuelCoke'))
        .key('G', TJAMetaBlocks.TIERED_GLASS.getItemVariant(BlockTieredGlass.CasingType.HV))
        .output(item('danknull:dank_null_panel_3'))
        .replace()
        .register()
// /dev/null/MK IV
crafting.shapedBuilder()
        .row('PPP')
        .row('PDP')
        .row('PPP')
        .key('P', item('danknull:dank_null_panel_3'))
        .key('D', item('danknull:dank_null_2'))
        .output(item('danknull:dank_null_3'))
        .replace()
        .register()
// centrifuge
mods.advancedrocketry.centrifuge.removeAll()
// chemical reactor
mods.advancedrocketry.chemical_reactor.removeAll()
// crystallizer
mods.advancedrocketry.crystallizer.removeAll()
// cutting machine
mods.advancedrocketry.cutting_machine.removeAll()
// electirc arc furnace
mods.advancedrocketry.electric_arc_furnace.removeAll()
// electrolyzer
mods.advancedrocketry.electrolyser.removeAll()
// lathe
mods.advancedrocketry.lathe.removeAll()
// precision assembler
mods.advancedrocketry.precision_assembler.removeAll()
// rolling machine
mods.advancedrocketry.rolling_machine.removeAll()
