import classes.TJMaterials
import com.fulltrix.gcyl.materials.GCYLMaterials
import gregicality.multiblocks.api.recipes.GCYMRecipeMaps
import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.blocks.BlockGlassCasing
import gregtech.common.blocks.MetaBlocks
import gregtech.common.items.MetaItems
import gregtech.common.metatileentities.MetaTileEntities
import tja.blocks.BlockTieredGlass
import tja.blocks.TJAMetaBlocks

// hopping bonsai pot
crafting.shapedBuilder()
        .row('PBP')
        .row('P P')
        .row('P P')
        .key('P', OreDictUnifier.get(OrePrefix.plateDouble, Materials.RhodiumPlatedPalladium))
        .key('B', item('bonsaitrees:bonsaipot'))
        .output(item('bonsaitrees:bonsaipot', 1))
        .replace()
        .register()
// memory chest (extended)
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row(' C ')
        .key('C', ore('circuitZpm'))
        .key('H', item('enderutilities:storage_0', 5))
        .output(item('enderutilities:storage_0', 6))
        .replace()
        .register()
// memory card (items) 12 B
crafting.shapedBuilder()
        .row('   ')
        .row('PCP')
        .row('PHP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('circuitZpm'))
        .key('H', MetaTileEntities.QUANTUM_CHEST[1].getStackForm())
        .output(item('enderutilities:enderpart', 54))
        .replace()
        .register()
// mob grinder
crafting.shapedBuilder()
        .row('PBP')
        .row('BHF')
        .row('PBP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.NaquadahAlloy))
        .key('B', OreDictUnifier.get(OrePrefix.turbineBlade, Materials.Osmium))
        .key('H', MetaTileEntities.HULL[GTValues.IV].getStackForm())
        .key('F', MetaItems.FIELD_GENERATOR_IV.getStackForm())
        .output(item('draconicevolution:grinder'))
        .replace()
        .register()
// advanced dislocator
RecipeMaps.ASSEMBLY_LINE_RECIPES.recipeBuilder()
        .inputs(item('draconicevolution:dislocator'))
        .input(OrePrefix.gem, Materials.EnderEye, 7)
        .input(OrePrefix.gem, Materials.EnderPearl, 3)
        .input(MetaItems.QUANTUM_EYE)
        .fluidInputs(GCYLMaterials.Draconium.getFluid(576))
        .outputs(item('draconicevolution:dislocator_advanced'))
        .EUt(GTValues.V[GTValues.LuV]).duration(200)
        .buildAndRegister()
// molten stellar alloy
GCYMRecipeMaps.ALLOY_BLAST_RECIPES.recipeBuilder()
        .blastFurnaceTemp(8100)
        .input(OrePrefix.dust, TJMaterials.StarMetalAlloy, 5)
        .input(OrePrefix.dust, Materials.Americium, 4)
        .input(OrePrefix.dust, Materials.NetherStar)
        .fluidOutputs(TJMaterials.StellarAlloy.getFluid(1440))
        .EUt(2430).duration(420)
        .buildAndRegister()
// stellar alloy ingot
RecipeMaps.FLUID_SOLIDFICATION_RECIPES.recipeBuilder()
        .notConsumable(MetaItems.SHAPE_MOLD_INGOT)
        .fluidInputs(TJMaterials.StellarAlloy.getFluid(144))
        .outputs(item('enderio:item_alloy_endergy_ingot', 3))
        .EUt(8).duration(20)
        .buildAndRegister()
// liquid starlight
RecipeMaps.EXTRACTOR_RECIPES.recipeBuilder()
        .input('gemAquamarine')
        .fluidOutputs(fluid('astralsorcery.liquidstarlight') * 5000)
        .EUt(2780).duration(40)
        .buildAndRegister()
RecipeMaps.EXTRACTOR_RECIPES.recipeBuilder()
        .inputs(item('astralsorcery:itemcraftingcomponent', 4))
        .fluidOutputs(fluid('astralsorcery.liquidstarlight') * 20000)
        .EUt(2780).duration(40)
        .buildAndRegister()
RecipeMaps.EXTRACTOR_RECIPES.recipeBuilder()
        .inputs(item('randomthings:ingredient', 2))
        .fluidOutputs(fluid('astralsorcery.liquidstarlight') * 50000)
        .EUt(2780).duration(40)
        .buildAndRegister()
// resonating gem
RecipeMaps.BLAST_RECIPES.recipeBuilder()
        .blastFurnaceTemp(7000)
        .input('gemAquamarine')
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 6000)
        .outputs(item('astralsorcery:itemcraftingcomponent', 4))
        .EUt(6000).duration(1000)
        .buildAndRegister()
// celestial crystal cluster
RecipeMaps.LARGE_CHEMICAL_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .inputs(item('astralsorcery:itemrockcrystalsimple'), item('astralsorcery:itemcraftingcomponent', 2))
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 1000)
        .outputs(item('astralsorcery:blockcelestialcrystals', 4))
        .EUt(30000).duration(500)
        .buildAndRegister()
// starmetal
RecipeMaps.BLAST_RECIPES.recipeBuilder()
        .circuitMeta(0)
        .blastFurnaceTemp(7000)
        .input('dustAstralStarmetal')
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 6000)
        .outputs(item('astralsorcery:itemcraftingcomponent', 1))
        .EUt(6000).duration(1000)
        .buildAndRegister()
// hot starmetal alloy ingot
RecipeMaps.BLAST_RECIPES.recipeBuilder()
        .blastFurnaceTemp(7600)
        .input(OrePrefix.ingot, Materials.NaquadahAlloy)
        .inputs(item('astralsorcery:itemcraftingcomponent', 1))
        .output(OrePrefix.ingotHot, TJMaterials.StarMetalAlloy, 2)
        .EUt(30720).duration(1000)
        .buildAndRegister()
// celestial altar
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blockaltar', 2))
mods.astralsorcery.starlight_altar.attunementRecipeBuilder()
        .row('S   S')
        .row(' G G ')
        .row(' MRM ')
        .row(' DID ')
        .row('I   I')
        .key('S', ore('dustAstralStarmetal'))
        .key('G', item('astralsorcery:itemcraftingcomponent', 4))
        .key('M', item('astralsorcery:blockmarble', 6))
        .key('R', item('astralsorcery:itemtunedcelestialcrystal'))
        .key('D', OreDictUnifier.get(OrePrefix.plateDouble, Materials.RhodiumPlatedPalladium))
        .key('I', ore('ingotAstralStarmetal'))
        .output(item('astralsorcery:blockaltar', 2))
        .starlight(500)
        .craftTime(300)
        .register()
// containment chalice
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blockchalice'))
mods.astralsorcery.starlight_altar.constellationRecipeBuilder()
        .row('IG GI')
        .row('ATMTA')
        .row(' T T ')
        .row('SDDDS')
        .row('II II')
        .key('I', ore('ingotAstralStarmetal'))
        .key('G', item('astralsorcery:itemcraftingcomponent', 4))
        .key('A', item('astralsorcery:itemcraftingcomponent'))
        .key('T', MetaBlocks.TRANSPARENT_CASING.getItemVariant(BlockGlassCasing.CasingType.LAMINATED_GLASS)) // TODO replace with tungsten reinforced glass
        .key('M', MetaTileEntities.TUNGSTENSTEEL_DRUM.getStackForm())
        .key('S', ore('dustAstralStarmetal'))
        .key('D', OreDictUnifier.get(OrePrefix.plateDouble, Materials.RhodiumPlatedPalladium))
        .output(item('astralsorcery:blockchalice'))
        .starlight(450)
        .craftTime(300)
        .register()
// iridescent altar
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blockaltar', 3))
mods.astralsorcery.starlight_altar.constellationRecipeBuilder()
        .row('MO OM')
        .row('GMLMG')
        .row(' SRS ')
        .row('GMLMG')
        .row('MO OM')
        .key('M', item('astralsorcery:blockmarble', 6))
        .key('O', item('astralsorcery:blockblackmarble'))
        .key('G', item('astralsorcery:itemcraftingcomponent', 4))
        .key('L', item('astralsorcery:itemcraftingcomponent', 3))
        .key('S', OreDictUnifier.get(OrePrefix.plate, TJMaterials.StarMetalAlloy))
        .key('R', item('astralsorcery:itemtunedcelestialcrystal'))
        .output(item('astralsorcery:blockaltar', 3))
        .starlight(800)
        .craftTime(400)
        .register()
// emerald /dank/null panel
crafting.shapedBuilder()
        .row('ECE')
        .row('CGC')
        .row('ECE')
        .key('E', ore('blockEmerald'))
        .key('C', ore('blockFuelCoke'))
        .key('G', TJAMetaBlocks.TIERED_GLASS.getItemVariant(BlockTieredGlass.CasingType.IV))
        .output(item('danknull:dank_null_panel_5'))
        .replace()
        .register()
// /dev/null/MK VI
crafting.shapedBuilder()
        .row('PPP')
        .row('PDP')
        .row('PPP')
        .key('P', item('danknull:dank_null_panel_5'))
        .key('D', item('danknull:dank_null_4'))
        .output(item('danknull:dank_null_5'))
        .replace()
        .register()