import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.MarkerMaterials
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.items.MetaItems
import gregtech.common.metatileentities.MetaTileEntities
import tja.blocks.BlockTieredGlass
import tja.blocks.TJAMetaBlocks

// super tank I
crafting.shapedBuilder()
        .row('CSC')
        .row('SHS')
        .row('CPC')
        .key('C', ore('circuitLv'))
        .key('S', OreDictUnifier.get(OrePrefix.plate, Materials.Steel))
        .key('H', MetaTileEntities.HULL[GTValues.LV].getStackForm())
        .key('P', MetaItems.ELECTRIC_PUMP_LV.getStackForm())
        .output(MetaTileEntities.QUANTUM_TANK[0].getStackForm())
        .replace()
        .register()
// diode
crafting.shapedBuilder()
        .row(' G ')
        .row('CDC')
        .row(' G ')
        .key('G', ore('paneGlass'))
        .key('C', OreDictUnifier.get(OrePrefix.wireFine, Materials.Copper))
        .key('D', OreDictUnifier.get(OrePrefix.dustSmall, Materials.Gallium))
        .output(MetaItems.DIODE.getStackForm())
        .register()
// basic fluid drilling rig
mods.gregtech.assembler.removeByInput(120,
        [metaitem('hull.mv'), metaitem('frameSteel') * 4, metaitem('circuit.good_electronic') * 4, metaitem('electric.motor.mv') * 4,
         metaitem('electric.pump.mv') * 4, metaitem('gearVanadiumSteel') * 4, metaitem('circuit.integrated').withNbt(['Configuration': 2])], null)
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(MetaItems.ELECTRIC_MOTOR_LV, 4)
        .input(MetaItems.ELECTRIC_PUMP_LV, 4)
        .input(OrePrefix.gear, Materials.Cobalt, 2)
        .input(MetaTileEntities.HULL[GTValues.LV])
        .input(OrePrefix.frameGt, Materials.Steel)
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV)
        .output(MetaTileEntities.BASIC_FLUID_DRILLING_RIG)
        .EUt(30).duration(400)
        .buildAndRegister()
// farming station
crafting.removeByOutput(item('enderio:block_farm_station'))
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(0)
        .inputs(item('enderio:item_material', 41), item('minecraft:diamond_hoe'))
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV, 2)
        .input(MetaTileEntities.HULL[GTValues.LV])
        .outputs(item('enderio:block_farm_station'))
        .EUt(30).duration(160)
        .buildAndRegister()
// tool casing
crafting.addShapeless(item('thermalfoundation:material', 640), [item('actuallyadditions:item_misc', 16)])
// item dislocator
crafting.removeByOutput(item('draconicevolution:magnet'))
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV, 2)
        .input(OrePrefix.dust, Materials.Redstone, 2)
        .inputs(item('enderio:item_alloy_ingot') * 4)
        .outputs(item('draconicevolution:magnet'))
        .EUt(28).duration(100)
        .buildAndRegister()
// Z-logic controller
crafting.shapedBuilder()
        .row('SIS')
        .row('DZD')
        .row('DRD')
        .key('S', item('enderio:item_alloy_ingot', 7))
        .key('I', OreDictUnifier.get(OrePrefix.ingot, Materials.Iron))
        .key('D', OreDictUnifier.get(OrePrefix.dust, Materials.Silicon))
        .key('Z', item('minecraft:skull', 2))
        .key('R', OreDictUnifier.get(OrePrefix.block, Materials.Redstone))
        .output(item('enderio:item_material', 41))
        .register()
// ender capacitor (enhanced)
crafting.shapedBuilder()
        .row(' E ')
        .row('VCV')
        .row('OVO')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderPearl))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', ore('circuitMv'))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:endercapacitor', 1))
        .replace()
        .register()
// inactive ender core (enhanced)
crafting.shapedBuilder()
        .row('OVO')
        .row('VCV')
        .row('OVO')
        .key('O', ore('obsidian'))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', ore('circuitMv'))
        .output(item('enderutilities:enderpart', 11))
        .replace()
        .register()
// ender bow
crafting.shapedBuilder()
        .row('RV ')
        .row('RCV')
        .row('RV ')
        .key('R', item('enderutilities:enderpart', 21))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', item('enderutilities:enderpart', 11))
        .output(item('enderutilities:enderbow'))
        .replace()
        .register()
// ender lasso
crafting.shapedBuilder()
        .row('RR ')
        .row('RC ')
        .row('  P')
        .key('R', item('enderutilities:enderpart', 21))
        .key('C', item('enderutilities:enderpart', 11))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:enderlasso'))
        .replace()
        .register()
// elite ender pearl
crafting.shapedBuilder()
        .row('FVF')
        .row('VPV')
        .row('FCF')
        .key('F', ore('feather'))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('P', item('enderutilities:enderpearlreusable'))
        .key('C', item('enderutilities:enderpart', 10))
        .output(item('enderutilities:enderpearlreusable', 1))
        .replace()
        .register()
// ender porter
crafting.shapedBuilder()
        .row('EVE')
        .row('VCV')
        .row('EVE')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderEye))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', item('enderutilities:enderpart', 16))
        .output(item('enderutilities:enderporter'))
        .replace()
        .register()
// nullifier - 1 / 9
crafting.shapedBuilder()
        .row('CLC')
        .row('PDP')
        .row('CLC')
        .key('C', ore('chestWood'))
        .key('L', item('minecraft:lava_bucket'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('D', item('danknull:dank_null_1'))
        .output(item('enderutilities:nullifier'))
        .replace()
        .register()
// item pickup manager - pre: 1 LC: 0
crafting.shapedBuilder()
        .row('VHV')
        .row('VEV')
        .row('VRV')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('H', item('minecraft:hopper'))
        .key('E', item('minecraft:ender_chest'))
        .key('R', item('minecraft:comparator'))
        .output(item('enderutilities:pickupmanager'))
        .replace()
        .register()
// syringe (empty)
crafting.shapedBuilder()
        .row('V  ')
        .row(' G ')
        .row('  E')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('G', ore('blockGlass'))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:syringe'))
        .replace()
        .register()
// energy bridge resonator
crafting.shapedBuilder()
        .row('VGV')
        .row('GCG')
        .row('VVV')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('G', ore('blockGlass'))
        .key('C', item('enderutilities:enderpart', 16))
        .output(item('enderutilities:energy_bridge'))
        .replace()
        .register()
// crafting station
crafting.shapedBuilder()
        .row('FTF')
        .row('VCV')
        .row('OVO')
        .key('F', item('enderutilities:machine_0'))
        .key('T', item('minecraft:crafting_table'))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', item('enderutilities:enderpart', 11))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:machine_1', 2))
        .replace()
        .register()
// molecular exciter
crafting.shapedBuilder()
        .row('VVV')
        .row('GCR')
        .row('VVV')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('G', ore('blockGlass'))
        .key('C', item('enderutilities:enderpart', 11))
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .output(item('enderutilities:molecular_exciter'))
        .replace()
        .register()
// electrical steel ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron)
        .input(OrePrefix.dust, Materials.Silicon)
        .outputs(item('enderio:item_alloy_ingot'))
        .EUt(30).duration(160)
        .buildAndRegister()
// energetic alloy ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Gold, 2)
        .input(OrePrefix.dust, Materials.Glowstone)
        .outputs(item('enderio:item_alloy_ingot', 1) * 2)
        .EUt(30).duration(160)
        .buildAndRegister()
// vibrant alloy ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_alloy_ingot', 1) * 2)
        .input(OrePrefix.gem, Materials.EnderPearl)
        .outputs(item('enderio:item_alloy_ingot', 2) * 2)
        .EUt(30).duration(160)
        .buildAndRegister()
// redstone alloy ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.Redstone)
        .input(OrePrefix.dust, Materials.Silicon)
        .outputs(item('enderio:item_alloy_ingot', 3))
        .EUt(30).duration(160)
        .buildAndRegister()
// conductive iron ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.Redstone)
        .input(OrePrefix.ingot, Materials.Iron)
        .outputs(item('enderio:item_alloy_ingot', 4))
        .EUt(30).duration(160)
        .buildAndRegister()
// pulsating iron ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron)
        .input(OrePrefix.dust, Materials.Uranium)
        .outputs(item('enderio:item_alloy_ingot', 5))
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron)
        .input(OrePrefix.ingot, Materials.Uranium)
        .outputs(item('enderio:item_alloy_ingot', 5))
        .EUt(30).duration(160)
        .buildAndRegister()
// dark steel ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Steel)
        .input(OrePrefix.block, Materials.Obsidian)
        .outputs(item('enderio:item_alloy_ingot', 6))
        .EUt(30).duration(160)
        .buildAndRegister()
// soularium ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('minecraft:soul_sand'))
        .input(OrePrefix.ingot, Materials.Gold)
        .outputs(item('enderio:item_alloy_ingot', 7))
        .EUt(30).duration(160)
        .buildAndRegister()
// grains of infinity
RecipeMaps.ARC_FURNACE_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.Coke, 64)
        .fluidInputs(fluid('fire_water') * 100)
        .outputs(item('enderio:item_material', 20) * 64)
        .EUt(28).duration(120)
        .buildAndRegister()
// grains of prescience
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_material', 19))
        .outputs(item('enderio:item_material', 34))
        .EUt(30).duration(160)
        .buildAndRegister()
// grains of piezallity
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_material', 14))
        .outputs(item('enderio:item_material', 36))
        .EUt(30).duration(160)
        .buildAndRegister()
// grains of the end
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_material', 16))
        .outputs(item('enderio:item_material', 37))
        .EUt(30).duration(160)
        .buildAndRegister()
// organic green dye
crafting.shapedBuilder()
        .row(' G ')
        .row('G G')
        .row(' G ')
        .key('G', item('minecraft:tallgrass', 1))
        .output(item('enderio:item_material', 48))
        .register()
// organic brown dye
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input("treeSapling", 4)
        .input(OrePrefix.gem, Materials.Charcoal)
        .outputs(item('enderio:item_material', 49) * 2)
        .EUt(30).duration(160)
        .buildAndRegister()
// organic black dye
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('minecraft:tallgrass', 1) * 2)
        .input(OrePrefix.gem, Materials.Coal)
        .outputs(item('enderio:item_material', 50) * 2)
        .EUt(30).duration(160)
        .buildAndRegister()
// soul powder
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_alloy_ingot', 7))
        .outputs(item('enderio:item_material', 74))
        .EUt(30).duration(160)
        .buildAndRegister()
// advanced item filter
crafting.shapedBuilder()
        .row('RDR')
        .row('DID')
        .row('RDR')
        .key('R', OreDictUnifier.get(OrePrefix.plate, Materials.Redstone))
        .key('D', OreDictUnifier.get(OrePrefix.plate, Materials.Diamond))
        .key('I', item('enderio:item_basic_item_filter'))
        .output(item('enderio:item_advanced_item_filter'))
        .replace()
        .register()
// big item filter
crafting.shapedBuilder()
        .row('ARA')
        .row('RIR')
        .row('ARA')
        .key('A', OreDictUnifier.get(OrePrefix.plate, Materials.Aluminium))
        .key('R', OreDictUnifier.get(OrePrefix.plate, Materials.Redstone))
        .key('I', item('enderio:item_basic_item_filter'))
        .output(item('enderio:item_big_item_filter'))
        .replace()
        .register()
// fused quartz
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.gem, Materials.NetherQuartz, 4)
        .outputs(item('enderio:block_fused_quartz'))
        .EUt(30).duration(160)
        .buildAndRegister()
// blank dark steel upgrade
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_alloy_ingot', 6))
        .input(OrePrefix.plateDouble, Materials.Steel)
        .outputs(item('enderio:item_dark_steel_upgrade'))
        .EUt(30).duration(100)
        .buildAndRegister()
// soul binder
crafting.shapedBuilder()
        .row('SHS')
        .row('HCH')
        .row('SHS')
        .key('S', item('enderio:item_alloy_ingot', 7))
        .key('H', ore('itemSkull'))
        .key('C', item('enderio:item_material', 53))
        .output(item('enderio:block_soul_binder'))
        .replace()
        .register()
// liquid xp
RecipeMaps.EXTRACTOR_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_solidified_experience') * 64)
        .fluidOutputs(fluid('xpjuice') * 10000)
        .EUt(30).duration(100)
        .buildAndRegister()
// enhanced machine chassis
crafting.shapelessBuilder()
        .input([ore('ingotDarkSteel'), item('enderio:item_material', 1)])
        .output(item('enderio:item_material', 54))
        .register()
// atomic reconstructor
crafting.removeByOutput(item('actuallyadditions:block_atomic_reconstructor'))
mods.actuallyadditions.atomic_reconstructor.removeAll()
// crusher
crafting.removeByOutput(item('actuallyadditions:block_grinder'))
mods.actuallyadditions.crusher.removeAll()
// double crusher
crafting.removeByOutput(item('actuallyadditions:block_grinder_double'))
// restonia crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Redstone)
        .outputs(item('actuallyadditions:block_crystal'))
        .EUt(8).duration(20)
        .buildAndRegister()
// palis crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Lapis)
        .outputs(item('actuallyadditions:block_crystal', 1))
        .EUt(8).duration(20)
        .buildAndRegister()
// diamatine crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Diamond)
        .outputs(item('actuallyadditions:block_crystal', 2))
        .EUt(8).duration(20)
        .buildAndRegister()
// void crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Coal)
        .outputs(item('actuallyadditions:block_crystal', 3))
        .EUt(8).duration(20)
        .buildAndRegister()
// emeradic crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Emerald)
        .outputs(item('actuallyadditions:block_crystal', 4))
        .EUt(8).duration(20)
        .buildAndRegister()
// enori crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Iron)
        .outputs(item('actuallyadditions:block_crystal', 5))
        .EUt(8).duration(20)
        .buildAndRegister()
// item laser relay
crafting.shapedBuilder()
        .row('OEO')
        .row('CWC')
        .row('OEO')
        .key('O', ore('obsidian'))
        .key('E', OreDictUnifier.get(OrePrefix.block, Materials.Emerald))
        .key('C', item('actuallyadditions:item_crystal', 4))
        .key('W', item('actuallyadditions:item_misc', 8))
        .output(item('actuallyadditions:block_laser_relay_item') * 4)
        .register()
// fluid laser relay
crafting.shapedBuilder()
        .row('OLO')
        .row('CWC')
        .row('OLO')
        .key('O', ore('obsidian'))
        .key('L', OreDictUnifier.get(OrePrefix.block, Materials.Lapis))
        .key('C', item('actuallyadditions:item_crystal', 1))
        .key('W', item('actuallyadditions:item_misc', 8))
        .output(item('actuallyadditions:block_laser_relay_fluids') * 4)
        .register()
// ethetic green block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .inputs(item('minecraft:quartz_block', 1))
        .outputs(item('actuallyadditions:block_testifi_bucks_green_wall'))
        .EUt(8).duration(20)
        .buildAndRegister()
// ethetic quartz
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.NetherQuartz)
        .outputs(item('actuallyadditions:block_testifi_bucks_white_wall'))
        .EUt(8).duration(20)
        .buildAndRegister()
// prismarine shard
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.gem, Materials.NetherQuartz)
        .outputs(item('minecraft:prismarine_shard'))
        .EUt(8).duration(20)
        .buildAndRegister()
// nether wart
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .inputs(item('minecraft:red_mushroom'))
        .outputs(item('minecraft:nether_wart'))
        .EUt(8).duration(20)
        .buildAndRegister()
// leather
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .inputs(item('minecraft:rotten_flesh'))
        .outputs(item('minecraft:leather'))
        .EUt(8).duration(20)
        .buildAndRegister()
// soul sand
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input('sand')
        .outputs(item('minecraft:soul_sand'))
        .EUt(8).duration(20)
        .buildAndRegister()
// diamond hook
crafting.shapedBuilder()
        .row(' PP')
        .row(' HP')
        .row('P  ')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Diamond))
        .key('H', item('hooked:hook', 1))
        .output(item('hooked:hook', 2))
        .replace()
        .register()
// red hook
crafting.shapedBuilder()
        .row('PPB')
        .row(' HP')
        .row('P P')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Redstone))
        .key('B', item('actuallyadditions:block_crystal'))
        .key('H', item('hooked:hook', 2))
        .output(item('hooked:hook', 3))
        .replace()
        .register()
// lapis /dank/null panel
crafting.shapedBuilder()
        .row('LCL')
        .row('CGC')
        .row('LCL')
        .key('L', ore('blockLapis'))
        .key('C', ore('blockFuelCoke'))
        .key('G', TJAMetaBlocks.TIERED_GLASS.getItemVariant(BlockTieredGlass.CasingType.LV))
        .output(item('danknull:dank_null_panel_1'))
        .replace()
        .register()
// /dev/null/MK II
crafting.shapedBuilder()
        .row('PPP')
        .row('PDP')
        .row('PPP')
        .key('P', item('danknull:dank_null_panel_1'))
        .key('D', item('danknull:dank_null_0'))
        .output(item('danknull:dank_null_1'))
        .replace()
        .register()