import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.items.MetaItems
import gregtech.common.metatileentities.MetaTileEntities
import tja.blocks.BlockTieredGlass
import tja.blocks.TJAMetaBlocks

// dolly
crafting.shapedBuilder()
        .row(' PV')
        .row('P V')
        .row('VVS')
        .key('P', MetaItems.ELECTRIC_PISTON_MV.getStackForm())
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('S', ore('blockSlime'))
        .output(item('enderutilities:dolly'))
        .replace()
        .register()
// small memory chest
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row('   ')
        .key('C', ore('circuitHv'))
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('enderutilities:storage_0'))
        .replace()
        .register()
// memory chest
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row('   ')
        .key('C', ore('circuitEv'))
        .key('H', item('enderutilities:storage_0'))
        .output(item('enderutilities:storage_0', 1))
        .replace()
        .register()
// handy chest (small)
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row(' C ')
        .key('C', ore('circuitHv'))
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('enderutilities:storage_0', 3))
        .replace()
        .register()
// handy chest (normal)
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row(' C ')
        .key('C', ore('circuitEv'))
        .key('H', item('enderutilities:storage_0', 3))
        .output(item('enderutilities:storage_0', 4))
        .replace()
        .register()
// memory card (items) 8 B
crafting.shapedBuilder()
        .row('   ')
        .row('PCP')
        .row('PHP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('circuitEv'))
        .key('H', MetaTileEntities.HULL[GTValues.EV].getStackForm())
        .output(item('enderutilities:enderpart', 52))
        .replace()
        .register()
// handy bag (large)
crafting.shapedBuilder()
        .row('PHP')
        .row('HCH')
        .row('PHP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('H', item('enderutilities:handybag'))
        .key('C', ore('circuitEv'))
        .output(item('enderutilities:handybag', 1))
        .replace()
        .register()
// pyrotheum dust
crafting.removeByOutput(item('thermalfoundation:material', 1024))
// cryotheum dust
crafting.removeByOutput(item('thermalfoundation:material', 1025))
// empowerer
crafting.removeByOutput(item('actuallyadditions:block_empowerer'))
mods.actuallyadditions.empowerer.removeAll()
// empowered restonia crystal
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_crystal'), item('minecraft:brick') * 2, item('minecraft:netherbrick') * 2)
        .input(OrePrefix.dust, Materials.Redstone, 2)
        .fluidInputs(Materials.Polyethylene.getFluid(32))
        .outputs(item('actuallyadditions:item_crystal_empowered'))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered restonia crystal block
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:block_crystal'), item('minecraft:brick_block') * 4, item('minecraft:nether_brick') * 4)
        .input(OrePrefix.block, Materials.Redstone, 2)
        .fluidInputs(Materials.Polyethylene.getFluid(288))
        .outputs(item('actuallyadditions:block_crystal_empowered'))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered palis crystal
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_crystal', 1))
        .input('gemPrismarine', 2)
        .input(OrePrefix.gem, Materials.Lapis, 2)
        .fluidInputs(Materials.Polyethylene.getFluid(32))
        .outputs(item('actuallyadditions:item_crystal_empowered', 1))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered palis crystal block
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:block_crystal', 1))
        .input('blockPrismarine', 4)
        .input(OrePrefix.block, Materials.Lapis, 2)
        .fluidInputs(Materials.Polyethylene.getFluid(288))
        .outputs(item('actuallyadditions:block_crystal_empowered', 1))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered diamatine crystal
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_crystal', 2))
        .input(OrePrefix.ingot, Materials.Clay, 2)
        .fluidInputs(Materials.Polyethylene.getFluid(32))
        .outputs(item('actuallyadditions:item_crystal_empowered', 2))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered diamatine crystal block
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:block_crystal', 2))
        .input(OrePrefix.block, Materials.Clay, 4)
        .fluidInputs(Materials.Polyethylene.getFluid(288))
        .outputs(item('actuallyadditions:block_crystal_empowered', 2))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered void crystal
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_crystal', 3))
        .input(OrePrefix.gem, Materials.Charcoal, 2)
        .input(OrePrefix.gem, Materials.Coke, 2)
        .fluidInputs(Materials.Polyethylene.getFluid(32))
        .outputs(item('actuallyadditions:item_crystal_empowered', 3))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered void crystal block
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:block_crystal', 3))
        .input(OrePrefix.block, Materials.Charcoal, 2)
        .input(OrePrefix.block, Materials.Coke, 2)
        .fluidInputs(Materials.Polyethylene.getFluid(288))
        .outputs(item('actuallyadditions:block_crystal_empowered', 3))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered emeradic crystal
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_crystal', 4))
        .input('slimeball', 2)
        .input(MetaItems.PLANT_BALL, 2)
        .fluidInputs(Materials.Polyethylene.getFluid(32))
        .outputs(item('actuallyadditions:item_crystal_empowered', 4))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered emeradic crystal block
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:block_crystal', 4))
        .input('blockSlime', 2)
        .input(MetaItems.PLANT_BALL, 18)
        .fluidInputs(Materials.Polyethylene.getFluid(288))
        .outputs(item('actuallyadditions:block_crystal_empowered', 4))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered enori crystal
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_crystal', 5))
        .input('dustSnow', 2)
        .input('stone', 2)
        .fluidInputs(Materials.Polyethylene.getFluid(32))
        .outputs(item('actuallyadditions:item_crystal_empowered', 5))
        .EUt(120).duration(160)
        .buildAndRegister()
// empowered enori crystal block
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:block_crystal', 5), item('minecraft:snow') * 4)
        .input('stone', 18)
        .fluidInputs(Materials.Polyethylene.getFluid(288))
        .outputs(item('actuallyadditions:block_crystal_empowered', 5))
        .EUt(120).duration(160)
        .buildAndRegister()
// iron /dank/null panel
crafting.shapedBuilder()
        .row('ICI')
        .row('CGC')
        .row('ICI')
        .key('I', ore('blockIron'))
        .key('C', ore('blockFuelCoke'))
        .key('G', TJAMetaBlocks.TIERED_GLASS.getItemVariant(BlockTieredGlass.CasingType.MV))
        .output(item('danknull:dank_null_panel_2'))
        .replace()
        .register()
// /dev/null/MK III
crafting.shapedBuilder()
        .row('PPP')
        .row('PDP')
        .row('PPP')
        .key('P', item('danknull:dank_null_panel_2'))
        .key('D', item('danknull:dank_null_1'))
        .output(item('danknull:dank_null_2'))
        .replace()
        .register()