import appeng.core.Api
import classes.TJMaterials
import classes.TJMetaTileEntities
import gregtech.api.GTValues
import gregtech.api.items.toolitem.ToolHelper
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.MarkerMaterials
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.api.unification.stack.UnificationEntry
import gregtech.common.blocks.BlockMachineCasing
import gregtech.common.blocks.BlockMetalCasing
import gregtech.common.blocks.BlockSteamCasing
import gregtech.common.blocks.MetaBlocks
import gregtech.common.items.MetaItems
import gregtech.common.items.ToolItems
import gregtech.common.metatileentities.MetaTileEntities
import net.minecraft.item.ItemStack

// use to damage GT tools in crafting
def toolTransform = { ItemStack stack ->
    ToolHelper.damageItem(stack, null)
    return stack // don't forgot to return the item or it'll be consumed
}

// steam motor
crafting.shapedBuilder()
        .row('SPR')
        .row('PRP')
        .row('IPS')
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.Wood))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Bronze))
        .key('R', OreDictUnifier.get(OrePrefix.stick, Materials.Iron))
        .key('I', OreDictUnifier.get(OrePrefix.ingot, Materials.Iron))
        .output(item('technological_journey:steammotor'))
        .register()
// steam piston
crafting.shapedBuilder()
        .row('GSS')
        .row('GMB')
        .row('PPP')
        .key('G', OreDictUnifier.get(OrePrefix.gearSmall, Materials.Iron))
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.Wood))
        .key('M', item('technological_journey:steammotor'))
        .key('B', OreDictUnifier.get(OrePrefix.plate, Materials.Bronze))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Iron))
        .output(item('technological_journey:steampiston'))
        .register()
// hot iron ingot
furnace.add(ore('ingotIron'), item('technological_journey:hotiron'))
// wrought iron
crafting.addShapeless(OreDictUnifier.get(OrePrefix.ingot, Materials.WroughtIron), [ore('toolHammer'), item('technological_journey:hotiron')])
// unfired clay brick
crafting.addShapeless(OreDictUnifier.get(OrePrefix.dust, TJMaterials.UnfiredClay), [OreDictUnifier.get(OrePrefix.ingot, Materials.Clay), MetaItems.WOODEN_FORM_BRICK.getStackForm()])
crafting.shapedBuilder()
        .row('CCC')
        .row('CBC')
        .row('CCC')
        .key('C', OreDictUnifier.get(OrePrefix.ingot, Materials.Clay))
        .key('B', MetaItems.WOODEN_FORM_BRICK.getStackForm())
        .output(OreDictUnifier.get(OrePrefix.dust, TJMaterials.UnfiredClay, 8))
        .register()
// brick
furnace.removeByOutput(item('minecraft:brick'))
furnace.add(OreDictUnifier.get(OrePrefix.dust, TJMaterials.UnfiredClay), item('minecraft:brick'))
// glass
furnace.add(OreDictUnifier.get(OrePrefix.dust, Materials.QuartzSand), item('minecraft:glass'))
// glass lens
crafting.shapedBuilder()
        .row('FfF')
        .row('FGF')
        .row('FDF')
        .key('F', OreDictUnifier.get(OrePrefix.gem, Materials.Flint))
        .key('f', ore('craftingToolFile').transform(toolTransform))
        .key('G', ore('blockGlass'))
        .key('D', OreDictUnifier.get(OrePrefix.gem, Materials.Diamond))
        .output(OreDictUnifier.get(OrePrefix.craftingLens, MarkerMaterials.Color.White))
        .register()
// industrial primitive blast furnace
crafting.shapedBuilder()
        .row('BFB')
        .row('FEF')
        .row('BFB')
        .key('B', MetaBlocks.METAL_CASING.getItemVariant(BlockMetalCasing.MetalCasingType.PRIMITIVE_BRICKS))
        .key('F', item('minecraft:furnace'))
        .key('E', MetaTileEntities.PRIMITIVE_BLAST_FURNACE.getStackForm())
        .output(TJMetaTileEntities.INDUSTRIAL_PRIMITIVE_BLAST_FURNACE.getStackForm())
        .register()
// portal to the void
crafting.shapedBuilder()
        .row('OIO')
        .row('IPI')
        .row('OIO')
        .key('O', ore('obsidian'))
        .key('I', item('minecraft:diamond'))
        .key('P', item('minecraft:iron_pickaxe'))
        .output(item('simplevoidworld:portal'))
        .replace()
        .register()
// transparant conduit facade
crafting.shapedBuilder()
        .row('   ')
        .row(' FV')
        .row('   ')
        .key('F', item('enderio:item_conduit_facade'))
        .key('V', Api.INSTANCE.definitions().blocks().quartzVibrantGlass().maybeStack(1).get())
        .output(item('enderio:item_conduit_facade', 2))
        .replace()
        .register()
crafting.shapedBuilder()
        .row('BBB')
        .row('BVB')
        .row('BBB')
        .key('B', item('enderio:item_material', 4))
        .key('V', Api.INSTANCE.definitions().blocks().quartzVibrantGlass().maybeStack(1).get())
        .output(item('enderio:item_conduit_facade', 2))
        .register()
// invisible block (decoration block)
crafting.replaceShapeless(item('enderio:block_decoration1', 15), [item('enderio:item_conduit_facade', 2)])
// yeta wrench
crafting.shapedBuilder()
        .row(' I ')
        .row(' T ')
        .row('I I')
        .key('I', OreDictUnifier.get(OrePrefix.ingot, Materials.Iron))
        .key('T', OreDictUnifier.get(OrePrefix.ingot, Materials.Tin))
        .output(item('enderio:item_yeta_wrench'))
        .replace()
        .register()
// ender fluid conduit
crafting.shapedBuilder()
        .row('BBB')
        .row('PCP')
        .row('BBB')
        .key('B', item('enderio:item_material', 4))
        .key('P', item('enderio:item_alloy_nugget', 5))
        .key('C', item('enderio:item_liquid_conduit', 1))
        .output(item('enderio:item_liquid_conduit', 2) * 8)
        .replace()
        .register()
crafting.shapedBuilder()
        .row('BBB')
        .row('PCP')
        .row('BBB')
        .key('B', item('enderio:item_material', 4))
        .key('P', item('enderio:item_alloy_nugget', 5))
        .key('C', ore('fusedQuartz'))
        .output(item('enderio:item_liquid_conduit', 2) * 8)
        .register()
// grindstone
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blockmachine', 1))
crafting.shapedBuilder()
        .row(' I ')
        .row('POS')
        .row('PPM')
        .key('I', OreDictUnifier.get(OrePrefix.dust, Materials.Iron))
        .key('P', OreDictUnifier.get(OrePrefix.plank, Materials.Wood))
        .key('O', item('minecraft:stone'))
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.Wood))
        .key('M', item('technological_journey:steammotor'))
        .output(item('astralsorcery:blockmachine', 1))
        .register()
// dense rubber sheet
RecipeMaps.FORGE_HAMMER_RECIPES.recipeBuilder()
        .input(OrePrefix.plate, Materials.Rubber, 9)
        .output(OrePrefix.plateDense, Materials.Rubber)
        .EUt(16).duration(200)
        .buildAndRegister()
// crushed black quartz
furnace.add(ore(new UnificationEntry(OrePrefix.dust, Materials.Quartzite).toString()), item('actuallyadditions:item_dust', 7))
// steam macerator
crafting.shapedBuilder()
        .row('PBP')
        .row('BHB')
        .row('MBM')
        .key('P', item('technological_journey:steampiston'))
        .key('B', OreDictUnifier.get(OrePrefix.pipeSmallFluid, Materials.Bronze))
        .key('H', MetaBlocks.STEAM_CASING.getItemVariant(BlockSteamCasing.SteamCasingType.BRONZE_HULL))
        .key('M', item('technological_journey:steammotor'))
        .output(MetaTileEntities.STEAM_MACERATOR_BRONZE.getStackForm())
        .replace()
        .register()
// high pressure steam macerator
crafting.shapedBuilder()
        .row('PBP')
        .row('BHB')
        .row('MBM')
        .key('P', item('technological_journey:steampiston'))
        .key('B', OreDictUnifier.get(OrePrefix.pipeSmallFluid, Materials.Steel))
        .key('H', MetaBlocks.STEAM_CASING.getItemVariant(BlockSteamCasing.SteamCasingType.STEEL_HULL))
        .key('M', item('technological_journey:steammotor'))
        .output(MetaTileEntities.STEAM_MACERATOR_STEEL.getStackForm())
        .replace()
        .register()
// high pressure steam compressor
crafting.shapedBuilder()
        .row('BBB')
        .row('MHP')
        .row('BBB')
        .key('P', item('technological_journey:steampiston'))
        .key('B', OreDictUnifier.get(OrePrefix.pipeSmallFluid, Materials.Steel))
        .key('H', MetaBlocks.STEAM_CASING.getItemVariant(BlockSteamCasing.SteamCasingType.STEEL_HULL))
        .key('M', item('technological_journey:steammotor'))
        .output(MetaTileEntities.STEAM_COMPRESSOR_STEEL.getStackForm())
        .replace()
        .register()
// steam compressor
crafting.shapedBuilder()
        .row('BBB')
        .row('MHP')
        .row('BBB')
        .key('P', item('technological_journey:steampiston'))
        .key('B', OreDictUnifier.get(OrePrefix.pipeSmallFluid, Materials.Bronze))
        .key('H', MetaBlocks.STEAM_CASING.getItemVariant(BlockSteamCasing.SteamCasingType.BRONZE_HULL))
        .key('M', item('technological_journey:steammotor'))
        .output(MetaTileEntities.STEAM_COMPRESSOR_BRONZE.getStackForm())
        .replace()
        .register()
// steam extractor
crafting.shapedBuilder()
        .row('BBB')
        .row('PHG')
        .row('BBB')
        .key('B', OreDictUnifier.get(OrePrefix.pipeSmallFluid, Materials.Bronze))
        .key('P', item('technological_journey:steampiston'))
        .key('H', MetaBlocks.STEAM_CASING.getItemVariant(BlockSteamCasing.SteamCasingType.BRONZE_HULL))
        .key('G', item('minecraft:glass'))
        .output(MetaTileEntities.STEAM_EXTRACTOR_BRONZE.getStackForm())
        .replace()
        .register()
// steam mixer
crafting.shapedBuilder()
        .row('GRG')
        .row('PBP')
        .row('BHB')
        .key('G', item('minecraft:glass'))
        .key('R', OreDictUnifier.get(OrePrefix.rotor, Materials.Bronze))
        .key('P', item('technological_journey:steampiston'))
        .key('B', OreDictUnifier.get(OrePrefix.pipeSmallFluid, Materials.Bronze))
        .key('H', MetaBlocks.STEAM_CASING.getItemVariant(BlockSteamCasing.SteamCasingType.BRONZE_HULL))
        .output(TJMetaTileEntities.STEAM_MIXER.getStackForm())
        .register()
// high pressure steam mixer
crafting.shapedBuilder()
        .row('GRG')
        .row('PBP')
        .row('BHB')
        .key('G', item('minecraft:glass'))
        .key('R', OreDictUnifier.get(OrePrefix.rotor, Materials.Steel))
        .key('P', item('technological_journey:steampiston'))
        .key('B', OreDictUnifier.get(OrePrefix.pipeSmallFluid, Materials.Steel))
        .key('H', MetaBlocks.STEAM_CASING.getItemVariant(BlockSteamCasing.SteamCasingType.STEEL_HULL))
        .output(TJMetaTileEntities.HIGH_PRESSURE_STEAM_MIXER.getStackForm())
        .register()
// steam chunk miner
crafting.shapedBuilder()
        .row('BBB')
        .row('PHP')
        .row('RBR')
        .key('B', OreDictUnifier.get(OrePrefix.pipeNormalFluid, Materials.Bronze))
        .key('P', item('technological_journey:steampiston'))
        .key('H', MetaBlocks.STEAM_CASING.getItemVariant(BlockSteamCasing.SteamCasingType.BRONZE_HULL))
        .key('R', OreDictUnifier.get(OrePrefix.rotor, Materials.Bronze))
// rubber sheet
RecipeMaps.COMPRESSOR_RECIPES.recipeBuilder()
        .input(MetaItems.STICKY_RESIN, 4)
        .output(OrePrefix.plate, Materials.Rubber)
        .EUt(16).duration(200)
        .buildAndRegister()
// glass bottle
crafting.shapedBuilder()
        .row('G G')
        .row(' G ')
        .key('G', ore('blockGlass'))
        .output(item('minecraft:glass_bottle'))
        .register()
// ulv machine hull
crafting.shapedBuilder()
        .row('WWW')
        .row('CHC')
        .key('W', OreDictUnifier.get(OrePrefix.plate, Materials.WroughtIron))
        .key('C', OreDictUnifier.get(OrePrefix.cableGtSingle, Materials.Lead))
        .key('H', MetaBlocks.MACHINE_CASING.getItemVariant(BlockMachineCasing.MachineCasingType.ULV))
        .output(MetaTileEntities.HULL[GTValues.ULV].getStackForm())
        .replace()
        .register()
// ulv input bus
crafting.shapedBuilder()
        .row(' C ')
        .row('wHh')
        .key('C', MetaTileEntities.BRONZE_CRATE.getStackForm())
        .key('w', ore('craftingToolWrench').transform(toolTransform))
        .key('H', MetaTileEntities.HULL[GTValues.ULV].getStackForm())
        .key('h', ore('craftingToolHardHammer').transform(toolTransform))
        .output(MetaTileEntities.ITEM_IMPORT_BUS[GTValues.ULV].getStackForm())
        .register()
// ulv output bus
crafting.shapedBuilder()
        .row('wHh')
        .row(' C ')
        .key('C', MetaTileEntities.BRONZE_CRATE.getStackForm())
        .key('w', ore('craftingToolWrench').transform(toolTransform))
        .key('H', MetaTileEntities.HULL[GTValues.ULV].getStackForm())
        .key('h', ore('craftingToolHardHammer').transform(toolTransform))
        .output(MetaTileEntities.ITEM_EXPORT_BUS[GTValues.ULV].getStackForm())
        .register()
// ulv input hatch
crafting.shapedBuilder()
        .row(' T ')
        .row('wHh')
        .key('T', MetaTileEntities.BRONZE_DRUM.getStackForm())
        .key('w', ore('craftingToolWrench').transform(toolTransform))
        .key('H', MetaTileEntities.HULL[GTValues.ULV].getStackForm())
        .key('h', ore('craftingToolHardHammer').transform(toolTransform))
        .output(MetaTileEntities.FLUID_IMPORT_HATCH[GTValues.ULV].getStackForm())
        .register()
// ulv output hatch
crafting.shapedBuilder()
        .row('wHh')
        .row(' T ')
        .key('T', MetaTileEntities.BRONZE_DRUM.getStackForm())
        .key('w', ore('craftingToolWrench').transform(toolTransform))
        .key('H', MetaTileEntities.HULL[GTValues.ULV].getStackForm())
        .key('h', ore('craftingToolHardHammer').transform(toolTransform))
        .output(MetaTileEntities.FLUID_EXPORT_HATCH[GTValues.ULV].getStackForm())
        .register()
// nether quartz dust
mods.astralsorcery.grindstone.recipeBuilder()
        .input(ore('oreNetherQuartz'))
        .output(OreDictUnifier.get(OrePrefix.dust, Materials.NetherQuartz, 2))
        .secondaryChance(0.5F)
        .weight(5)
        .register()
// coal dust
mods.astralsorcery.grindstone.recipeBuilder()
        .input(ore('oreCoal'))
        .output(OreDictUnifier.get(OrePrefix.dust, Materials.Coal))
        .secondaryChance(0.5F)
        .weight(5)
        .register()
// copper dust
mods.astralsorcery.grindstone.recipeBuilder()
        .input(ore('oreCopper'))
        .output(OreDictUnifier.get(OrePrefix.dust, Materials.Copper))
        .secondaryChance(0.5F)
        .weight(5)
        .register()
mods.astralsorcery.grindstone.recipeBuilder()
        .input(ore('ingotCopper'))
        .output(OreDictUnifier.get(OrePrefix.dust, Materials.Copper))
        .weight(5)
        .register()
// tin dust
mods.astralsorcery.grindstone.recipeBuilder()
        .input(ore('oreTin'))
        .output(OreDictUnifier.get(OrePrefix.dust, Materials.Tin))
        .secondaryChance(0.5F)
        .weight(5)
        .register()
mods.astralsorcery.grindstone.recipeBuilder()
        .input(ore('ingotTin'))
        .output(OreDictUnifier.get(OrePrefix.dust, Materials.Tin))
        .weight(5)
        .register()
// iron dust
mods.astralsorcery.grindstone.recipeBuilder()
        .input(ore('oreIron'))
        .output(OreDictUnifier.get(OrePrefix.dust, Materials.Iron))
        .secondaryChance(0.5F)
        .weight(5)
        .register()
mods.astralsorcery.grindstone.recipeBuilder()
        .input(ore('ingotIron'))
        .output(OreDictUnifier.get(OrePrefix.dust, Materials.Iron))
        .weight(5)
        .register()
// nickel ingot
mods.astralsorcery.grindstone.recipeBuilder()
        .input(ore('ingotNickel'))
        .output(OreDictUnifier.get(OrePrefix.dust, Materials.Nickel))
        .weight(5)
        .register()
// tree beacon
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blocktreebeacon'))
crafting.shapedBuilder()
        .row('CSC')
        .row('PCP')
        .row('PPP')
        .key('C', ore('circuitLv'))
        .key('S', ore('treeSapling'))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Steel))
        .output(item('astralsorcery:blocktreebeacon'))
        .register()
// adjustable storage unit
crafting.shapedBuilder()
        .row('PCP')
        .row('PSP')
        .row('PCP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', item('minecraft:comparator'))
        .key('S', item('actuallyadditions:block_giant_chest'))
        .output(item('enderutilities:asu'))
        .replace()
        .register()
// ender capacitor (basic)
crafting.shapedBuilder()
        .row(' E ')
        .row('PCP')
        .row('OPO')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderPearl))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('circuitLv'))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:endercapacitor'))
        .replace()
        .register()
// inactive ender core (basic)
crafting.shapedBuilder()
        .row('OPO')
        .row('PCP')
        .row('OPO')
        .key('O', ore('obsidian'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('circuitLv'))
        .output(item('enderutilities:enderpart', 10))
        .replace()
        .register()
// jailer module
crafting.shapedBuilder()
        .row('PBP')
        .row('B B')
        .row('PBP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('B', ore('barsIron'))
        .output(item('enderutilities:enderpart', 45))
        .replace()
        .register()
// link crystal (location)
crafting.shapedBuilder()
        .row('RGR')
        .row('GPG')
        .row('RGR')
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .key('G', ore('blockGlassGreen'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:linkcrystal'))
        .replace()
        .register()
// link crystal (block)
crafting.shapedBuilder()
        .row('RGR')
        .row('GPG')
        .row('RGR')
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .key('G', ore('blockGlassBlue'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:linkcrystal', 1))
        .replace()
        .register()
// link crystal (portal)
crafting.shapedBuilder()
        .row('RGR')
        .row('GPG')
        .row('RGR')
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .key('G', ore('blockGlassPurple'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:linkcrystal', 2))
        .replace()
        .register()
// chair wand
crafting.shapedBuilder()
        .row('S  ')
        .row(' P ')
        .row('  P')
        .key('S', ore('stairWood'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:chairwand'))
        .replace()
        .register()
// ender bucket
crafting.shapedBuilder()
        .row(' C ')
        .row('PBP')
        .row(' P ')
        .key('C', item('enderutilities:enderpart', 10))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('B', item('minecraft:bucket'))
        .output(item('enderutilities:enderbucket'))
        .replace()
        .register()
// inventory swapper
crafting.shapedBuilder()
        .row('RPR')
        .row('PCP')
        .row('NPN')
        .key('R', item('enderutilities:enderpart', 21))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('chestWood'))
        .key('N', item('minecraft:sticky_piston'))
        .output(item('enderutilities:inventoryswapper'))
        .replace()
        .register()
// quick stacker P: 1
crafting.shapedBuilder()
        .row('RNR')
        .row('PCP')
        .row('RNR')
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .key('N', item('minecraft:piston'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', item('minecraft:comparator'))
        .output(item('enderutilities:quickstacker'))
        .replace()
        .register()
// ruler
crafting.shapedBuilder()
        .row('P  ')
        .row('PS ')
        .row('PPP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('S', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:ruler'))
        .replace()
        .register()
// barrel
crafting.shapedBuilder()
        .row('PSP')
        .row('SCS')
        .row('PSP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('S', item('actuallyadditions:block_giant_chest'))
        .key('C', ore('chest'))
        .output(item('enderutilities:barrel'))
        .replace()
        .register()
// barrel label
crafting.shapedBuilder()
        .row('SSS')
        .row('SPS')
        .row('SSS')
        .key('S', ore('stickWood'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:enderpart', 70))
        .replace()
        .register()
// barrel capacity upgrade
crafting.shapedBuilder()
        .row('PCP')
        .row('CHC')
        .row('PCP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', item('actuallyadditions:block_giant_chest'))
        .key('H', item('enderutilities:barrel'))
        .output(item('enderutilities:enderpart', 72))
        .replace()
        .register()
// barrel void upgrade
crafting.shapedBuilder()
        .row('OOO')
        .row('OUO')
        .row('OOO')
        .key('O', ore('obsidian'))
        .key('U', item('storagedrawers:upgrade_void'))
        .output(item('enderutilities:enderpart', 73))
        .replace()
        .register()
// storage key
crafting.shapedBuilder()
        .row('PP ')
        .row('PN ')
        .row(' N ')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('N', item('enderio:item_alloy_nugget', 5))
        .output(item('enderutilities:enderpart', 80))
        .replace()
        .register()
// drawbridge
crafting.shapedBuilder()
        .row('PNP')
        .row('PNP')
        .row('PRP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('N', item('minecraft:sticky_piston'))
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .output(item('enderutilities:draw_bridge'))
        .replace()
        .register()
// advanced drawbridge
crafting.shapedBuilder()
        .row('PNP')
        .row('PNP')
        .row('PCP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('N', item('minecraft:sticky_piston'))
        .key('C', item('minecraft:comparator'))
        .output(item('enderutilities:draw_bridge', 1))
        .replace()
        .register()
// ender elevator (white)
crafting.shapedBuilder()
        .row('WBW')
        .row('PNP')
        .row('PRP')
        .key('W', ore('wool'))
        .key('B', item('minecraft:stone_pressure_plate'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('N', item('minecraft:sticky_piston'))
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .output(item('enderutilities:ender_elevator') * 2)
        .replace()
        .register()
// inserter
crafting.shapedBuilder()
        .row('PPP')
        .row('GGG')
        .row('PPP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('G', ore('blockGlass'))
        .output(item('enderutilities:inserter'))
        .replace()
        .register()
// inserter (filtered)
crafting.shapedBuilder()
        .row('PPP')
        .row('GCG')
        .row('PPP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('G', ore('blockGlass'))
        .key('C', item('minecraft:comparator'))
        .output(item('enderutilities:inserter', 1))
        .replace()
        .register()
// ender furnace
crafting.shapedBuilder()
        .row('OPO')
        .row('PFP')
        .row('OCO')
        .key('O', ore('obsidian'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('F', item('minecraft:furnace'))
        .key('C', item('enderutilities:enderpart', 10))
        .output(item('enderutilities:machine_0'))
        .replace()
        .register()
// ender infuser
crafting.shapedBuilder()
        .row('PHP')
        .row('PNP')
        .row('OFO')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('H', item('minecraft:hopper'))
        .key('N', item('minecraft:piston'))
        .key('O', ore('obsidian'))
        .key('F', item('minecraft:furnace'))
        .output(item('enderutilities:machine_1'))
        .replace()
        .register()
// tool workstation
crafting.shapedBuilder()
        .row('PSP')
        .row('PTP')
        .row('OCO')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('S', ore('slimeball'))
        .key('T', item('minecraft:crafting_table'))
        .key('O', ore('obsidian'))
        .key('C', ore('chestWood'))
        .output(item('enderutilities:machine_1', 1))
        .replace()
        .register()
// advanced quick stacker
crafting.shapedBuilder()
        .row('NPN')
        .row('PQP')
        .row('NPN')
        .key('N', item('minecraft:piston'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('Q', item('enderutilities:quickstacker'))
        .output(item('enderutilities:machine_1', 3))
        .replace()
        .register()
// phasing block
crafting.shapedBuilder()
        .row('BBB')
        .row('BRB')
        .row('BPB')
        .key('B', item('minecraft:stonebrick'))
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:phasing'))
        .replace()
        .register()
// phasing block (inverted)
crafting.shapedBuilder()
        .row('BBB')
        .row('BTB')
        .row('BPB')
        .key('B', item('minecraft:stonebrick'))
        .key('T', item('minecraft:redstone_torch'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:phasing', 1))
        .replace()
        .register()
// portal frame
crafting.shapedBuilder()
        .row('GPG')
        .row('PRP')
        .row('GPG')
        .key('G', ore('blockGlass'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .output(item('enderutilities:frame') * 8)
        .replace()
        .register()
// sound block
crafting.shapedBuilder()
        .row('PMP')
        .row('M M')
        .row('PMP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('M', item('minecraft:noteblock'))
        .output(item('enderutilities:sound_block'))
        .replace()
        .register()
// extract speed upgrade
crafting.shapedBuilder()
        .row('III')
        .row('BNB')
        .row('BRB')
        .key('I', OreDictUnifier.get(OrePrefix.ingot, Materials.Iron))
        .key('B', OreDictUnifier.get(OrePrefix.ingot, Materials.Bronze))
        .key('N', item('minecraft:piston'))
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .output(item('enderio:item_extract_speed_upgrade'))
        .replace()
        .register()
// industrial machine chassis
crafting.shapelessBuilder()
        .input([ore('dyeBlack'), item('enderio:item_material')])
        .output(item('enderio:item_material', 1))
        .register()
// soul machine chassis
crafting.shapelessBuilder()
        .input([ore('dyeSoulMachine'), item('enderio:item_material', 1)])
        .output(item('enderio:item_material', 53))
        .register()
// station light
crafting.shapedBuilder()
        .row(' P ')
        .row('PGP')
        .row(' P ')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Iron))
        .key('G', OreDictUnifier.get(OrePrefix.block, Materials.Glowstone))
        .output(item('advancedrocketry:circlelight'))
        .replace()
        .register()
// iron hook
crafting.shapedBuilder()
        .row('PPH')
        .row(' IP')
        .row('I P')
        .key('P', OreDictUnifier.get(OrePrefix.plateDouble, Materials.Iron))
        .key('H', ToolItems.PICKAXE.get(Materials.Iron))
        .key('I', item('hooked:microcrafting', 3))\
        .output(item('hooked:hook', 1))
        .replace()
        .register()
// redstone /dank/null panel
crafting.shapedBuilder()
        .row('RCR')
        .row('CGC')
        .row('RCR')
        .key('R', ore('blockRedstone'))
        .key('C', ore('blockCoal'))
        .key('G', ore('blockGlass'))
        .output(item('danknull:dank_null_panel_0'))
        .replace()
        .register()
// /dev/null/
crafting.shapedBuilder()
        .row('PPP')
        .row('PCP')
        .row('PPP')
        .key('P', item('danknull:dank_null_panel_0'))
        .key('C', ore('blockCoal'))
        .output(item('danknull:dank_null_0'))
        .replace()
        .register()
// steam alloy smelter
crafting.removeByOutput(MetaTileEntities.STEAM_ALLOY_SMELTER_BRONZE.getStackForm())
// high pressure steam alloy smelter
crafting.removeByOutput(MetaTileEntities.STEAM_ALLOY_SMELTER_STEEL.getStackForm())
// enderio alloy smelter
mods.enderio.alloy_smelter.removeAll()
// enderio sag mill
mods.enderio.sag_mill.removeAll()
mods.enderio.sag_mill_grinding.removeAll()
// enderio combustion generator
mods.enderio.fluid_fuel.removeAll()