package postInit.lines

import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.material.MarkerMaterials
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix

// canola oil
RecipeMaps.EXTRACTOR_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_canola_seed') * 40)
        .fluidOutputs(fluid('canolaoil') * 4000)
        .EUt(8).duration(150)
        .buildAndRegister()
RecipeMaps.EXTRACTOR_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_misc', 13) * 25)
        .fluidOutputs(fluid('canolaoil') * 5000)
        .EUt(8).duration(150)
        .buildAndRegister()
// refined canola oil
RecipeMaps.FERMENTING_RECIPES.recipeBuilder()
        .fluidInputs(fluid('canolaoil') * 40000)
        .fluidOutputs(fluid('refinedcanolaoil') * 40000)
        .EUt(16).duration(300)
        .buildAndRegister()
// crystallized canola seed
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .inputs(item('actuallyadditions:item_canola_seed') * 30)
        .outputs(item('actuallyadditions:item_misc', 23) * 30)
        .EUt(8).duration(20)
        .buildAndRegister()
// crystallized oil
RecipeMaps.CHEMICAL_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_misc', 23) * 8)
        .fluidInputs(fluid('refinedcanolaoil') * 10000)
        .fluidOutputs(fluid('crystaloil') * 10000)
        .EUt(16).duration(300)
        .buildAndRegister()
// empowered oil
RecipeMaps.CHEMICAL_RECIPES.recipeBuilder()
        .fluidInputs(Materials.Creosote.getFluid(5000), fluid('crystaloil') * 5000)
        .fluidOutputs(fluid('empoweredoil') * 10000)
        .EUt(16).duration(300)
        .buildAndRegister()
// bio diesel
RecipeMaps.CHEMICAL_RECIPES.recipeBuilder()
        .input(OrePrefix.dustTiny, Materials.SodiumHydroxide)
        .fluidInputs(Materials.Ethanol.getFluid(1000), Materials.Creosote.getFluid(6000))
        .fluidOutputs(Materials.BioDiesel.getFluid(6000), Materials.Glycerol.getFluid(1000))
        .EUt(30).duration(600)
        .buildAndRegister()
RecipeMaps.CHEMICAL_RECIPES.recipeBuilder()
        .input(OrePrefix.dustTiny, Materials.SodiumHydroxide)
        .fluidInputs(Materials.Methanol.getFluid(1000), Materials.Creosote.getFluid(6000))
        .fluidOutputs(Materials.BioDiesel.getFluid(6000), Materials.Glycerol.getFluid(1000))
        .EUt(30).duration(600)
        .buildAndRegister()
RecipeMaps.CHEMICAL_RECIPES.recipeBuilder()
        .input(OrePrefix.dustTiny, Materials.SodiumHydroxide)
        .fluidInputs(Materials.Ethanol.getFluid(1000), fluid('empoweredoil') * 20000)
        .fluidOutputs(Materials.BioDiesel.getFluid(20000), Materials.Glycerol.getFluid(1000))
        .EUt(20).duration(120)
        .buildAndRegister()
RecipeMaps.CHEMICAL_RECIPES.recipeBuilder()
        .input(OrePrefix.dustTiny, Materials.SodiumHydroxide)
        .fluidInputs(Materials.Methanol.getFluid(1000), fluid('empoweredoil') * 20000)
        .fluidOutputs(Materials.BioDiesel.getFluid(20000), Materials.Glycerol.getFluid(1000))
        .EUt(20).duration(120)
        .buildAndRegister()
RecipeMaps.LARGE_CHEMICAL_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.SodiumHydroxide)
        .fluidInputs(Materials.Ethanol.getFluid(9000), Materials.Creosote.getFluid(54000))
        .fluidOutputs(Materials.BioDiesel.getFluid(54000), Materials.Glycerol.getFluid(9000))
        .EUt(30).duration(5400)
        .buildAndRegister()
RecipeMaps.LARGE_CHEMICAL_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.SodiumHydroxide)
        .fluidInputs(Materials.Methanol.getFluid(9000), Materials.Creosote.getFluid(54000))
        .fluidOutputs(Materials.BioDiesel.getFluid(54000), Materials.Glycerol.getFluid(9000))
        .EUt(30).duration(5400)
        .buildAndRegister()
RecipeMaps.LARGE_CHEMICAL_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.SodiumHydroxide)
        .fluidInputs(Materials.Ethanol.getFluid(9000), fluid('empoweredoil') * 180000)
        .fluidOutputs(Materials.BioDiesel.getFluid(180000), Materials.Glycerol.getFluid(9000))
        .EUt(20).duration(1080)
        .buildAndRegister()
RecipeMaps.LARGE_CHEMICAL_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.SodiumHydroxide)
        .fluidInputs(Materials.Methanol.getFluid(9000), fluid('empoweredoil') * 180000)
        .fluidOutputs(Materials.BioDiesel.getFluid(180000), Materials.Glycerol.getFluid(9000))
        .EUt(20).duration(1080)
        .buildAndRegister()