package postInit.lines

import com.fulltrix.gcyl.materials.GCYLMaterials
import gregtech.api.fluids.store.FluidStorageKeys
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.items.MetaItems

// LV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.LVSuperconductorBase, 3)
        .input(OrePrefix.pipeTinyFluid, Materials.Steel)
        .input(MetaItems.ELECTRIC_PUMP_LV, 2)
        .fluidInputs(Materials.Nitrogen.getFluid(1000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.LVSuperconductor, 3)
        .EUt(30).duration(350)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.LVSuperconductorBase, 9)
        .input(OrePrefix.pipeTinyFluid, Materials.Steel)
        .input(MetaItems.ELECTRIC_PUMP_LV)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 3000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.LVSuperconductor, 9)
        .EUt(32).duration(120)
        .buildAndRegister()
// MV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.MVSuperconductorBase, 3)
        .input(OrePrefix.pipeTinyFluid, Materials.StainlessSteel, 2)
        .input(MetaItems.ELECTRIC_PUMP_MV, 2)
        .fluidInputs(Materials.Nitrogen.getFluid(2000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.MVSuperconductor, 3)
        .EUt(120).duration(300)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.MVSuperconductorBase, 9)
        .input(OrePrefix.pipeTinyFluid, Materials.StainlessSteel)
        .input(MetaItems.ELECTRIC_PUMP_MV)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 3000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.MVSuperconductor, 9)
        .EUt(128).duration(120)
        .buildAndRegister()
// HV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.HVSuperconductorBase, 3)
        .input(OrePrefix.pipeTinyFluid, Materials.Titanium, 2)
        .input(MetaItems.ELECTRIC_PUMP_HV)
        .fluidInputs(Materials.Nitrogen.getFluid(2000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.HVSuperconductor, 3)
        .EUt(256).duration(200)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.HVSuperconductorBase, 9)
        .input(OrePrefix.pipeTinyFluid, Materials.Titanium)
        .input(MetaItems.ELECTRIC_PUMP_HV)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 3000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.HVSuperconductor, 9)
        .EUt(512).duration(120)
        .buildAndRegister()
// EV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.EVSuperconductorBase, 9)
        .input(OrePrefix.pipeTinyFluid, Materials.TungstenSteel, 6)
        .input(MetaItems.ELECTRIC_PUMP_EV, 2)
        .fluidInputs(Materials.Nitrogen.getFluid(FluidStorageKeys.LIQUID, 6000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.EVSuperconductor, 9)
        .EUt(480).duration(500)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.EVSuperconductorBase, 18)
        .input(OrePrefix.pipeTinyFluid, Materials.TungstenSteel, 6)
        .input(MetaItems.ELECTRIC_PUMP_EV, 2)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 3000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.EVSuperconductor, 18)
        .EUt(2048).duration(120)
        .buildAndRegister()
// IV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.IVSuperconductorBase, 6)
        .input(OrePrefix.pipeTinyFluid, GCYLMaterials.Enderium, 4)
        .input(MetaItems.ELECTRIC_PUMP_IV)
        .fluidInputs(Materials.Nitrogen.getFluid(FluidStorageKeys.LIQUID, 6000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.IVSuperconductor, 6)
        .EUt(1920).duration(300)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.IVSuperconductorBase, 12)
        .input(OrePrefix.pipeTinyFluid, GCYLMaterials.Enderium, 4)
        .input(MetaItems.ELECTRIC_PUMP_IV)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 4000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.IVSuperconductor, 12)
        .EUt(8192).duration(120)
        .buildAndRegister()