package postInit.lines

import com.fulltrix.gcyl.item.GCYLCoreItems
import com.fulltrix.gcyl.materials.GCYLMaterials
import gregicality.multiblocks.api.unification.GCYMMaterials
import gregtech.api.GTValues
import gregtech.api.fluids.store.FluidStorageKeys
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.items.MetaItems

int starlightCost = 4194304
// LV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.LVSuperconductorBase, 3)
        .input(OrePrefix.pipeTinyFluid, Materials.Steel)
        .input(MetaItems.ELECTRIC_PUMP_LV, 2)
        .fluidInputs(Materials.Nitrogen.getFluid(1000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.LVSuperconductor, 3)
        .EUt(30).duration(350)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.LVSuperconductorBase, 9)
        .input(OrePrefix.pipeTinyFluid, Materials.Steel)
        .input(MetaItems.ELECTRIC_PUMP_LV)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 3000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.LVSuperconductor, 9)
        .EUt(32).duration(120)
        .buildAndRegister()
// MV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.MVSuperconductorBase, 3)
        .input(OrePrefix.pipeTinyFluid, Materials.StainlessSteel, 2)
        .input(MetaItems.ELECTRIC_PUMP_MV, 2)
        .fluidInputs(Materials.Nitrogen.getFluid(2000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.MVSuperconductor, 3)
        .EUt(120).duration(300)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.MVSuperconductorBase, 9)
        .input(OrePrefix.pipeTinyFluid, Materials.StainlessSteel)
        .input(MetaItems.ELECTRIC_PUMP_MV)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 3000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.MVSuperconductor, 9)
        .EUt(128).duration(120)
        .buildAndRegister()
// HV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.HVSuperconductorBase, 3)
        .input(OrePrefix.pipeTinyFluid, Materials.Titanium, 2)
        .input(MetaItems.ELECTRIC_PUMP_HV)
        .fluidInputs(Materials.Nitrogen.getFluid(2000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.HVSuperconductor, 3)
        .EUt(256).duration(200)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.HVSuperconductorBase, 9)
        .input(OrePrefix.pipeTinyFluid, Materials.Titanium)
        .input(MetaItems.ELECTRIC_PUMP_HV)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 3000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.HVSuperconductor, 9)
        .EUt(512).duration(120)
        .buildAndRegister()
// EV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.EVSuperconductorBase, 9)
        .input(OrePrefix.pipeTinyFluid, Materials.TungstenSteel, 6)
        .input(MetaItems.ELECTRIC_PUMP_EV, 2)
        .fluidInputs(Materials.Nitrogen.getFluid(FluidStorageKeys.LIQUID, 6000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.EVSuperconductor, 9)
        .EUt(480).duration(500)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.EVSuperconductorBase, 18)
        .input(OrePrefix.pipeTinyFluid, Materials.TungstenSteel, 6)
        .input(MetaItems.ELECTRIC_PUMP_EV, 2)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 3000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.EVSuperconductor, 18)
        .EUt(2048).duration(120)
        .buildAndRegister()
// IV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.IVSuperconductorBase, 6)
        .input(OrePrefix.pipeTinyFluid, Materials.NiobiumTitanium, 4)
        .input(MetaItems.ELECTRIC_PUMP_IV)
        .fluidInputs(Materials.Nitrogen.getFluid(FluidStorageKeys.LIQUID, 6000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.IVSuperconductor, 6)
        .EUt(1920).duration(300)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.IVSuperconductorBase, 12)
        .input(OrePrefix.pipeTinyFluid, Materials.NiobiumTitanium, 4)
        .input(MetaItems.ELECTRIC_PUMP_IV)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 4000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.IVSuperconductor, 12)
        .EUt(8192).duration(120)
        .buildAndRegister()
// LuV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.LuVSuperconductorBase, 8)
        .input(OrePrefix.pipeTinyFluid, GCYLMaterials.Enderium, 5)
        .input(MetaItems.ELECTRIC_PUMP_LuV)
        .fluidInputs(Materials.Nitrogen.getFluid(FluidStorageKeys.LIQUID, 6000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.LuVSuperconductor, 8)
        .EUt(7680).duration(350)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.LuVSuperconductorBase, 16)
        .input(OrePrefix.pipeTinyFluid, GCYLMaterials.Enderium, 5)
        .input(MetaItems.ELECTRIC_PUMP_LuV)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 4000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.LuVSuperconductor, 16)
        .EUt(starlightCost).duration(120)
        .buildAndRegister()
// ZPM superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.ZPMSuperconductorBase, 16)
        .input(OrePrefix.pipeTinyFluid, Materials.Naquadah, 6)
        .input(MetaItems.ELECTRIC_PUMP_ZPM)
        .fluidInputs(Materials.Helium.getFluid(FluidStorageKeys.LIQUID, 8000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.ZPMSuperconductor, 16)
        .EUt(GTValues.VAOC[GTValues.LuV]).duration(400)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.ZPMSuperconductorBase, 32)
        .input(OrePrefix.pipeTinyFluid, Materials.Naquadah, 6)
        .input(MetaItems.ELECTRIC_PUMP_ZPM)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 8000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.ZPMSuperconductor, 32)
        .EUt(starlightCost).duration(120)
        .buildAndRegister()
// UV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.UVSuperconductorBase, 32)
        .input(OrePrefix.pipeNormalItem, Materials.Ultimet, 7)
        .input(MetaItems.ELECTRIC_PUMP_UV)
        .fluidInputs(Materials.Helium.getFluid(FluidStorageKeys.LIQUID, 10000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.UVSuperconductor, 32)
        .EUt(GTValues.VAOC[GTValues.ZPM]).duration(500)
        .buildAndRegister()
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.UVSuperconductorBase, 64)
        .input(OrePrefix.pipeNormalItem, Materials.Ultimet, 7)
        .input(MetaItems.ELECTRIC_PUMP_ZPM)
        .fluidInputs(fluid('astralsorcery.liquidstarlight') * 10000)
        .output(OrePrefix.wireGtSingle, GCYLMaterials.UVSuperconductor, 64)
        .EUt(starlightCost).duration(120)
        .buildAndRegister()
// UHV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.UHVSuperconductorBase, 32)
        .input(OrePrefix.pipeTinyFluid, GCYMMaterials.Zeron100, 8)
        .input(MetaItems.ELECTRIC_PUMP_UHV)
        .fluidInputs(Materials.Helium.getFluid(FluidStorageKeys.LIQUID, 12000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.UHVSuperconductor, 32)
        .EUt(GTValues.VAOC[GTValues.UV]).duration(500)
        .buildAndRegister()
// UEV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.UEVSuperconductorBase, 32)
        .input(OrePrefix.pipeTinyFluid, GCYLMaterials.Lafium, 9)
        .input(MetaItems.ELECTRIC_PUMP_UEV)
        .fluidInputs(GCYLMaterials.MicrocrystallizingHydrogen.getFluid(14000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.UEVSuperconductor, 32)
        .EUt(GTValues.VAOC[GTValues.UHV]).duration(500)
        .buildAndRegister()
// UIV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.UIVSuperconductorBase, 32)
        .input(OrePrefix.pipeTinyFluid, GCYLMaterials.TantalumHafniumSeaborgiumCarbide, 10)
        .input(MetaItems.ELECTRIC_PUMP_UIV)
        .fluidInputs(GCYLMaterials.MicrocrystallizingHydrogen.getFluid(16000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.UIVSuperconductor, 32)
        .EUt(GTValues.VAOC[GTValues.UEV]).duration(500)
        .buildAndRegister()
// UXV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.UXVSuperconductorBase, 32)
        .input(OrePrefix.pipeTinyFluid, Materials.Neutronium, 11)
        .input(MetaItems.ELECTRIC_PUMP_UXV)
        .fluidInputs(GCYLMaterials.MicrocrystallizingHydrogen.getFluid(18000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.UXVSuperconductor, 32)
        .EUt(GTValues.VAOC[GTValues.UIV]).duration(500)
        .buildAndRegister()
// OPV superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(1)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.OpVSuperconductorBase, 32)
        .input(OrePrefix.pipeTinyFluid, Materials.Neutronium, 12)
        .input(MetaItems.ELECTRIC_PUMP_OpV)
        .fluidInputs(GCYLMaterials.MicrocrystallizingHydrogen.getFluid(20000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.OpVSuperconductor, 32)
        .EUt(GTValues.VAOC[GTValues.UXV]).duration(500)
        .buildAndRegister()
// MAX superconductor
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(2)
        .input(OrePrefix.wireGtSingle, GCYLMaterials.OpVSuperconductorBase, 64)
        .input(OrePrefix.pipeTinyFluid, Materials.Neutronium, 13)
        .input(GCYLCoreItems.ELECTRIC_PUMP_MAX)
        .fluidInputs(GCYLMaterials.MicrocrystallizingHydrogen.getFluid(22000))
        .output(OrePrefix.wireGtSingle, GCYLMaterials.MAXSuperconductor, 64)
        .EUt(GTValues.VAOC[GTValues.OpV]).duration(500)
        .buildAndRegister()