package postInit.multiblock_recipes

import classes.MetaTileEntityPrimitiveAlloySmelter
import classes.TJMetaTileEntities
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.blocks.BlockMetalCasing
import gregtech.common.blocks.MetaBlocks
import gregtech.common.items.MetaItems

def alloyRecipes = MetaTileEntityPrimitiveAlloySmelter.PRIMITIVE_ALLOY_SMELTER_RECIPES
def pulsatingIronIngot = item('enderio:item_alloy_ingot', 5)

// primitive alloy smelter
crafting.shapedBuilder()
        .row('BMB')
        .row('M P')
        .row('BPB')
        .key('B', MetaBlocks.METAL_CASING.getItemVariant(BlockMetalCasing.MetalCasingType.PRIMITIVE_BRICKS))
        .key('M', item('technological_journey:steammotor'))
        .key('P', item('technological_journey:steampiston'))
        .output(TJMetaTileEntities.PRIMITIVE_ALLOY_SMELTER.getStackForm())
        .register()
// bronze ingot
alloyRecipes.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Copper, 3)
        .input(OrePrefix.ingot, Materials.Tin)
        .output(OrePrefix.ingot, Materials.Bronze, 4)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(600)
        .buildAndRegister()
// soldering alloy ingot
alloyRecipes.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Tin, 9)
        .input(OrePrefix.ingot, Materials.Antimony)
        .output(OrePrefix.ingot, Materials.SolderingAlloy, 10)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(600)
        .buildAndRegister()
// red alloy ingot
alloyRecipes.recipeBuilder()
        .input(OrePrefix.dust, Materials.Redstone, 4)
        .input(OrePrefix.ingot, Materials.Copper)
        .output(OrePrefix.ingot, Materials.RedAlloy)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(600)
        .buildAndRegister()
// wrought iron
alloyRecipes.recipeBuilder()
        .inputs(item('technological_journey:hotiron') * 4)
        .output(OrePrefix.ingot, Materials.WroughtIron, 4)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(150)
        .buildAndRegister()
// glass tube
alloyRecipes.recipeBuilder()
        .notConsumable(MetaItems.SHAPE_MOLD_BALL)
        .input(OrePrefix.dust, Materials.Glass, 4)
        .output(MetaItems.GLASS_TUBE, 4)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(150)
        .buildAndRegister()
alloyRecipes.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron)
        .input(OrePrefix.dust, Materials.Uranium)
        .outputs(pulsatingIronIngot)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(160)
        .buildAndRegister()
// fused quartz
alloyRecipes.recipeBuilder()
        .input(OrePrefix.gem, Materials.NetherQuartz, 4)
        .outputs(item('enderio:block_fused_quartz'))
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(160)
        .buildAndRegister()
alloyRecipes.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron)
        .input(OrePrefix.ingot, Materials.Uranium)
        .outputs(pulsatingIronIngot)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(160)
        .buildAndRegister()
alloyRecipes.recipeBuilder()
        .input(OrePrefix.dust, Materials.Iron)
        .input(OrePrefix.dust, Materials.Uranium)
        .outputs(pulsatingIronIngot)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(160)
        .buildAndRegister()
alloyRecipes.recipeBuilder()
        .input(OrePrefix.dust, Materials.Iron)
        .input(OrePrefix.ingot, Materials.Uranium)
        .outputs(pulsatingIronIngot)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(160)
        .buildAndRegister()
// invar ingot
alloyRecipes.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron, 2)
        .input(OrePrefix.ingot, Materials.Nickel)
        .output(OrePrefix.ingot, Materials.Invar, 3)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(160)
        .buildAndRegister()
// invar ingot
alloyRecipes.recipeBuilder()
        .input(OrePrefix.dust, Materials.Iron, 2)
        .input(OrePrefix.ingot, Materials.Nickel)
        .output(OrePrefix.ingot, Materials.Invar, 3)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(160)
        .buildAndRegister()
// invar ingot
alloyRecipes.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron, 2)
        .input(OrePrefix.dust, Materials.Nickel)
        .output(OrePrefix.ingot, Materials.Invar, 3)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(160)
        .buildAndRegister()
// invar ingot
alloyRecipes.recipeBuilder()
        .input(OrePrefix.dust, Materials.Iron, 2)
        .input(OrePrefix.dust, Materials.Nickel)
        .output(OrePrefix.ingot, Materials.Invar, 3)
        .fluidInputs(Materials.Steam.getFluid(1000))
        .duration(160)
        .buildAndRegister()
